import type { Locale } from '../../store/prefs'

export interface ActWord {
  id: string
  text: Record<Locale, string>
}

export interface ActPack {
  id: string
  words: ActWord[]
}

/**
 * Bilingual charades dictionaries — things you can act out with no words.
 * Big pools so freshPick rarely repeats across party nights.
 */
export const ACT_PACKS: ActPack[] = [
  {
    id: 'mix',
    words: [
      { id: 'm1', text: { en: 'Brushing teeth', fa: 'مسواک زدن' } },
      { id: 'm2', text: { en: 'Taking a selfie', fa: 'سلفی گرفتن' } },
      { id: 'm3', text: { en: 'Driving a car', fa: 'رانندگی' } },
      { id: 'm4', text: { en: 'Parallel parking', fa: 'پارک دوبل' } },
      { id: 'm5', text: { en: 'Fishing', fa: 'ماهیگیری' } },
      { id: 'm6', text: { en: 'Ironing clothes', fa: 'اتو کردن لباس' } },
      { id: 'm7', text: { en: 'Making tea', fa: 'چای دم کردن' } },
      { id: 'm8', text: { en: 'Eating spaghetti', fa: 'اسپاگتی خوردن' } },
      { id: 'm9', text: { en: 'Chopping onions', fa: 'پیاز خرد کردن' } },
      { id: 'm10', text: { en: 'Sneezing', fa: 'عطسه کردن' } },
      { id: 'm11', text: { en: 'Hiccups', fa: 'سکسکه' } },
      { id: 'm12', text: { en: 'Yawning', fa: 'خمیازه کشیدن' } },
      { id: 'm13', text: { en: 'Snoring', fa: 'خروپف' } },
      { id: 'm14', text: { en: 'Jump rope', fa: 'طناب زدن' } },
      { id: 'm15', text: { en: 'Push-ups', fa: 'شنا رفتن' } },
      { id: 'm16', text: { en: 'Yoga', fa: 'یوگا' } },
      { id: 'm17', text: { en: 'Swimming', fa: 'شنا کردن' } },
      { id: 'm18', text: { en: 'Riding a bike', fa: 'دوچرخه‌سواری' } },
      { id: 'm19', text: { en: 'Riding a motorcycle', fa: 'موتورسواری' } },
      { id: 'm20', text: { en: 'Rollercoaster', fa: 'ترن هوایی' } },
      { id: 'm21', text: { en: 'Stuck in an elevator', fa: 'گیر کردن در آسانسور' } },
      { id: 'm22', text: { en: 'Waiting in line', fa: 'در صف ایستادن' } },
      { id: 'm23', text: { en: 'Texting', fa: 'پیامک دادن' } },
      { id: 'm24', text: { en: 'Video call', fa: 'تماس تصویری' } },
      { id: 'm25', text: { en: 'Blowing out candles', fa: 'فوت کردن شمع' } },
      { id: 'm26', text: { en: 'Wrapping a gift', fa: 'کادو پیچیدن' } },
      { id: 'm27', text: { en: 'Opening a stuck jar', fa: 'باز کردن درِ شیشهٔ سفت' } },
      { id: 'm28', text: { en: 'Stepping on Lego', fa: 'پا گذاشتن روی لگو' } },
      { id: 'm29', text: { en: 'Slipping on ice', fa: 'سُر خوردن روی یخ' } },
      { id: 'm30', text: { en: 'Walking a dog', fa: 'سگ گردانی' } },
      { id: 'm31', text: { en: 'Watering plants', fa: 'آب دادن به گل‌ها' } },
      { id: 'm32', text: { en: 'Painting a wall', fa: 'رنگ زدن دیوار' } },
      { id: 'm33', text: { en: 'Changing a lightbulb', fa: 'عوض کردن لامپ' } },
      { id: 'm34', text: { en: 'Making the bed', fa: 'مرتب کردن تخت' } },
      { id: 'm35', text: { en: 'Washing dishes', fa: 'ظرف شستن' } },
      { id: 'm36', text: { en: 'Getting a haircut', fa: 'کوتاه کردن مو' } },
      { id: 'm37', text: { en: 'Shaving', fa: 'اصلاح صورت' } },
      { id: 'm38', text: { en: 'Applying makeup', fa: 'آرایش کردن' } },
      { id: 'm39', text: { en: 'Painting nails', fa: 'لاک زدن' } },
      { id: 'm40', text: { en: 'Tying shoelaces', fa: 'بستن بند کفش' } },
      { id: 'm41', text: { en: 'Umbrella in the wind', fa: 'چتر در باد' } },
      { id: 'm42', text: { en: 'Running for the bus', fa: 'دویدن دنبال اتوبوس' } },
      { id: 'm43', text: { en: 'Airport security check', fa: 'بازرسی فرودگاه' } },
      { id: 'm44', text: { en: 'Packing a suitcase', fa: 'بستن چمدان' } },
      { id: 'm45', text: { en: 'Karaoke', fa: 'کارائوکه' } },
      { id: 'm46', text: { en: 'Conducting an orchestra', fa: 'رهبری ارکستر' } },
      { id: 'm47', text: { en: 'Playing the violin', fa: 'ویولن زدن' } },
      { id: 'm48', text: { en: 'Milking a cow', fa: 'دوشیدن گاو' } },
      { id: 'm49', text: { en: 'Building a sandcastle', fa: 'قلعهٔ شنی ساختن' } },
      { id: 'm50', text: { en: 'Flying a kite', fa: 'بادبادک هوا کردن' } },
      { id: 'm51', text: { en: 'Bowling', fa: 'بولینگ' } },
      { id: 'm52', text: { en: 'Darts', fa: 'دارت' } },
      { id: 'm53', text: { en: 'Arm wrestling', fa: 'مچ‌اندازی' } },
      { id: 'm54', text: { en: 'Hot potato', fa: 'سیب‌زمینی داغ' } },
      { id: 'm55', text: { en: 'Hide and seek', fa: 'قایم‌باشک' } },
      { id: 'm56', text: { en: 'Tug of war', fa: 'طناب‌کشی' } },
    ],
  },
  {
    id: 'movies',
    words: [
      { id: 'v1', text: { en: 'Titanic', fa: 'تایتانیک' } },
      { id: 'v2', text: { en: 'Harry Potter', fa: 'هری پاتر' } },
      { id: 'v3', text: { en: 'Batman', fa: 'بتمن' } },
      { id: 'v4', text: { en: 'Spider-Man', fa: 'مرد عنکبوتی' } },
      { id: 'v5', text: { en: 'Frozen', fa: 'فروزن' } },
      { id: 'v6', text: { en: 'The Lion King', fa: 'شیرشاه' } },
      { id: 'v7', text: { en: 'Mr. Bean', fa: 'مستر بین' } },
      { id: 'v8', text: { en: 'Tom and Jerry', fa: 'تام و جری' } },
      { id: 'v9', text: { en: 'Friends', fa: 'سریال فرندز' } },
      { id: 'v10', text: { en: 'Game of Thrones', fa: 'بازی تاج‌وتخت' } },
      { id: 'v11', text: { en: 'Squid Game', fa: 'بازی مرکب' } },
      { id: 'v12', text: { en: 'Money Heist', fa: 'خانهٔ کاغذی' } },
      { id: 'v13', text: { en: 'Shrek', fa: 'شرک' } },
      { id: 'v14', text: { en: 'Avatar', fa: 'آواتار' } },
      { id: 'v15', text: { en: 'Jurassic Park', fa: 'پارک ژوراسیک' } },
      { id: 'v16', text: { en: 'The Godfather', fa: 'پدرخوانده' } },
      { id: 'v17', text: { en: 'Rocky', fa: 'راکی' } },
      { id: 'v18', text: { en: 'Terminator', fa: 'ترمیناتور' } },
      { id: 'v19', text: { en: 'Pirates of the Caribbean', fa: 'دزدان دریایی کارائیب' } },
      { id: 'v20', text: { en: 'Home Alone', fa: 'تنها در خانه' } },
      { id: 'v21', text: { en: 'Charlie Chaplin', fa: 'چارلی چاپلین' } },
      { id: 'v22', text: { en: 'Sherlock Holmes', fa: 'شرلوک هلمز' } },
      { id: 'v23', text: { en: 'James Bond', fa: 'جیمز باند' } },
      { id: 'v24', text: { en: 'Superman', fa: 'سوپرمن' } },
      { id: 'v25', text: { en: 'Joker', fa: 'جوکر' } },
      { id: 'v26', text: { en: 'Aladdin', fa: 'علاءالدین' } },
      { id: 'v27', text: { en: 'Cinderella', fa: 'سیندرلا' } },
      { id: 'v28', text: { en: 'Pinocchio', fa: 'پینوکیو' } },
      { id: 'v29', text: { en: 'Zorro', fa: 'زورو' } },
      { id: 'v30', text: { en: 'Dracula', fa: 'دراکولا' } },
      { id: 'v31', text: { en: 'SpongeBob', fa: 'باب‌اسفنجی' } },
      { id: 'v32', text: { en: 'The Matrix', fa: 'ماتریکس' } },
      { id: 'v33', text: { en: 'Forrest Gump', fa: 'فارست گامپ' } },
      { id: 'v34', text: { en: 'The Silence of the Lambs', fa: 'سکوت بره‌ها' } },
      { id: 'v35', text: { en: 'Breaking Bad', fa: 'برکینگ بد' } },
      { id: 'v36', text: { en: 'La Casa de Papel mask', fa: 'ماسک سالوادور دالی' } },
      { id: 'v37', text: { en: 'Toy Story', fa: 'داستان اسباب‌بازی' } },
      { id: 'v38', text: { en: 'Finding Nemo', fa: 'در جستجوی نمو' } },
      { id: 'v39', text: { en: 'Kung Fu Panda', fa: 'پاندای کونگ‌فوکار' } },
      { id: 'v40', text: { en: 'Madagascar', fa: 'ماداگاسکار' } },
      { id: 'v41', text: { en: 'Ratatouille', fa: 'راتاتویی' } },
      { id: 'v42', text: { en: 'Cars', fa: 'ماشین‌ها' } },
      { id: 'v43', text: { en: 'Up', fa: 'آپ (بالون‌ها)' } },
      { id: 'v44', text: { en: 'Minions', fa: 'مینیون‌ها' } },
      { id: 'v45', text: { en: 'Pink Panther', fa: 'پلنگ صورتی' } },
      { id: 'v46', text: { en: 'Popeye', fa: 'ملوان زبل' } },
      { id: 'v47', text: { en: 'Cinema ticket line', fa: 'صف بلیت سینما' } },
      { id: 'v48', text: { en: 'Slow-motion action scene', fa: 'صحنهٔ اکشن اسلوموشن' } },
    ],
  },
  {
    id: 'animals',
    words: [
      { id: 'a1', text: { en: 'Cat', fa: 'گربه' } },
      { id: 'a2', text: { en: 'Dog', fa: 'سگ' } },
      { id: 'a3', text: { en: 'Elephant', fa: 'فیل' } },
      { id: 'a4', text: { en: 'Giraffe', fa: 'زرافه' } },
      { id: 'a5', text: { en: 'Penguin', fa: 'پنگوئن' } },
      { id: 'a6', text: { en: 'Kangaroo', fa: 'کانگورو' } },
      { id: 'a7', text: { en: 'Snake', fa: 'مار' } },
      { id: 'a8', text: { en: 'Monkey', fa: 'میمون' } },
      { id: 'a9', text: { en: 'Lion', fa: 'شیر' } },
      { id: 'a10', text: { en: 'Eagle', fa: 'عقاب' } },
      { id: 'a11', text: { en: 'Owl', fa: 'جغد' } },
      { id: 'a12', text: { en: 'Spider', fa: 'عنکبوت' } },
      { id: 'a13', text: { en: 'Butterfly', fa: 'پروانه' } },
      { id: 'a14', text: { en: 'Crab', fa: 'خرچنگ' } },
      { id: 'a15', text: { en: 'Octopus', fa: 'هشت‌پا' } },
      { id: 'a16', text: { en: 'Shark', fa: 'کوسه' } },
      { id: 'a17', text: { en: 'Dolphin', fa: 'دلفین' } },
      { id: 'a18', text: { en: 'Turtle', fa: 'لاک‌پشت' } },
      { id: 'a19', text: { en: 'Rabbit', fa: 'خرگوش' } },
      { id: 'a20', text: { en: 'Squirrel', fa: 'سنجاب' } },
      { id: 'a21', text: { en: 'Bat', fa: 'خفاش' } },
      { id: 'a22', text: { en: 'Bear', fa: 'خرس' } },
      { id: 'a23', text: { en: 'Wolf', fa: 'گرگ' } },
      { id: 'a24', text: { en: 'Fox', fa: 'روباه' } },
      { id: 'a25', text: { en: 'Peacock', fa: 'طاووس' } },
      { id: 'a26', text: { en: 'Flamingo', fa: 'فلامینگو' } },
      { id: 'a27', text: { en: 'Woodpecker', fa: 'دارکوب' } },
      { id: 'a28', text: { en: 'Mosquito', fa: 'پشه' } },
      { id: 'a29', text: { en: 'Bee', fa: 'زنبور' } },
      { id: 'a30', text: { en: 'Ant', fa: 'مورچه' } },
      { id: 'a31', text: { en: 'Chameleon', fa: 'آفتاب‌پرست' } },
      { id: 'a32', text: { en: 'Sloth', fa: 'تنبل (حیوان)' } },
      { id: 'a33', text: { en: 'Hedgehog', fa: 'جوجه‌تیغی' } },
      { id: 'a34', text: { en: 'Camel', fa: 'شتر' } },
      { id: 'a35', text: { en: 'Horse', fa: 'اسب' } },
      { id: 'a36', text: { en: 'Donkey', fa: 'خر' } },
      { id: 'a37', text: { en: 'Rooster', fa: 'خروس' } },
      { id: 'a38', text: { en: 'Chicken', fa: 'مرغ' } },
      { id: 'a39', text: { en: 'Duck', fa: 'اردک' } },
      { id: 'a40', text: { en: 'Frog', fa: 'قورباغه' } },
      { id: 'a41', text: { en: 'Mouse', fa: 'موش' } },
      { id: 'a42', text: { en: 'Hamster', fa: 'همستر' } },
      { id: 'a43', text: { en: 'Parrot', fa: 'طوطی' } },
      { id: 'a44', text: { en: 'Gorilla', fa: 'گوریل' } },
      { id: 'a45', text: { en: 'T-Rex', fa: 'تیرانوزاروس' } },
      { id: 'a46', text: { en: 'Scorpion', fa: 'عقرب' } },
      { id: 'a47', text: { en: 'Seal', fa: 'فُک' } },
      { id: 'a48', text: { en: 'Goldfish', fa: 'ماهی قرمز' } },
    ],
  },
  {
    id: 'jobs',
    words: [
      { id: 'j1', text: { en: 'Doctor', fa: 'دکتر' } },
      { id: 'j2', text: { en: 'Teacher', fa: 'معلم' } },
      { id: 'j3', text: { en: 'Barber', fa: 'آرایشگر' } },
      { id: 'j4', text: { en: 'Taxi driver', fa: 'رانندهٔ تاکسی' } },
      { id: 'j5', text: { en: 'Chef', fa: 'سرآشپز' } },
      { id: 'j6', text: { en: 'Firefighter', fa: 'آتش‌نشان' } },
      { id: 'j7', text: { en: 'Ballerina', fa: 'بالرین' } },
      { id: 'j8', text: { en: 'Magician', fa: 'شعبده‌باز' } },
      { id: 'j9', text: { en: 'Referee', fa: 'داور' } },
      { id: 'j10', text: { en: 'Photographer', fa: 'عکاس' } },
      { id: 'j11', text: { en: 'Dentist', fa: 'دندان‌پزشک' } },
      { id: 'j12', text: { en: 'Plumber', fa: 'لوله‌کش' } },
      { id: 'j13', text: { en: 'DJ', fa: 'دی‌جی' } },
      { id: 'j14', text: { en: 'Bodybuilder', fa: 'بدنساز' } },
      { id: 'j15', text: { en: 'Fortune teller', fa: 'فالگیر' } },
      { id: 'j16', text: { en: 'Tour guide', fa: 'راهنمای تور' } },
      { id: 'j17', text: { en: 'Waiter', fa: 'گارسون' } },
      { id: 'j18', text: { en: 'Surgeon', fa: 'جراح' } },
      { id: 'j19', text: { en: 'Pilot', fa: 'خلبان' } },
      { id: 'j20', text: { en: 'Farmer', fa: 'کشاورز' } },
      { id: 'j21', text: { en: 'News anchor', fa: 'گویندهٔ خبر' } },
      { id: 'j22', text: { en: 'Traffic cop', fa: 'پلیس راهنمایی' } },
      { id: 'j23', text: { en: 'Street musician', fa: 'نوازندهٔ خیابانی' } },
      { id: 'j24', text: { en: 'Sculptor', fa: 'مجسمه‌ساز' } },
      { id: 'j25', text: { en: 'Tailor', fa: 'خیاط' } },
      { id: 'j26', text: { en: 'Blacksmith', fa: 'آهنگر' } },
      { id: 'j27', text: { en: 'Beekeeper', fa: 'زنبوردار' } },
      { id: 'j28', text: { en: 'Lifeguard', fa: 'نجات غریق' } },
      { id: 'j29', text: { en: 'Astronaut', fa: 'فضانورد' } },
      { id: 'j30', text: { en: 'Spy', fa: 'جاسوس' } },
      { id: 'j31', text: { en: 'Clown', fa: 'دلقک' } },
      { id: 'j32', text: { en: 'Ninja', fa: 'نینجا' } },
      { id: 'j33', text: { en: 'Pirate', fa: 'دزد دریایی' } },
      { id: 'j34', text: { en: 'Cowboy', fa: 'کابوی' } },
      { id: 'j35', text: { en: 'Sumo wrestler', fa: 'کشتی‌گیر سومو' } },
      { id: 'j36', text: { en: 'Opera singer', fa: 'خوانندهٔ اپرا' } },
      { id: 'j37', text: { en: 'Mime', fa: 'پانتومیم‌کار' } },
      { id: 'j38', text: { en: 'Cheerleader', fa: 'تشویق‌کننده' } },
      { id: 'j39', text: { en: 'Bouncer', fa: 'نگهبان کلاب' } },
      { id: 'j40', text: { en: 'Paparazzi', fa: 'پاپاراتزی' } },
      { id: 'j41', text: { en: 'Influencer', fa: 'اینفلوئنسر' } },
      { id: 'j42', text: { en: 'Gamer', fa: 'گیمر' } },
      { id: 'j43', text: { en: 'Librarian', fa: 'کتابدار' } },
      { id: 'j44', text: { en: 'Judge', fa: 'قاضی' } },
      { id: 'j45', text: { en: 'Boxer', fa: 'بوکسور' } },
      { id: 'j46', text: { en: 'Weightlifter', fa: 'وزنه‌بردار' } },
      { id: 'j47', text: { en: 'Goalkeeper', fa: 'دروازه‌بان' } },
      { id: 'j48', text: { en: 'Carpet seller', fa: 'فرش‌فروش' } },
    ],
  },
  {
    id: 'hard',
    words: [
      { id: 'h1', text: { en: 'Déjà vu', fa: 'دژاوو' } },
      { id: 'h2', text: { en: 'Gravity', fa: 'جاذبه' } },
      { id: 'h3', text: { en: 'Jealousy', fa: 'حسادت' } },
      { id: 'h4', text: { en: 'Wi-Fi', fa: 'وای‌فای' } },
      { id: 'h5', text: { en: 'Inflation', fa: 'تورم' } },
      { id: 'h6', text: { en: 'Monday morning', fa: 'صبح شنبه' } },
      { id: 'h7', text: { en: 'Insomnia', fa: 'بی‌خوابی' } },
      { id: 'h8', text: { en: 'Echo', fa: 'اکو' } },
      { id: 'h9', text: { en: 'Shadow', fa: 'سایه' } },
      { id: 'h10', text: { en: 'Time travel', fa: 'سفر در زمان' } },
      { id: 'h11', text: { en: 'Karma', fa: 'کارما' } },
      { id: 'h12', text: { en: 'Midlife crisis', fa: 'بحران میان‌سالی' } },
      { id: 'h13', text: { en: 'Procrastination', fa: 'اهمال‌کاری' } },
      { id: 'h14', text: { en: 'Claustrophobia', fa: 'تنگناهراسی' } },
      { id: 'h15', text: { en: 'Sunburn', fa: 'آفتاب‌سوختگی' } },
      { id: 'h16', text: { en: 'Static electricity', fa: 'الکتریسیتهٔ ساکن' } },
      { id: 'h17', text: { en: 'Nostalgia', fa: 'نوستالژی' } },
      { id: 'h18', text: { en: 'Low battery', fa: 'باتری کم' } },
      { id: 'h19', text: { en: 'Buffering', fa: 'بافرینگ' } },
      { id: 'h20', text: { en: 'Spoiler', fa: 'اسپویل' } },
      { id: 'h21', text: { en: 'Ghosting', fa: 'گوستینگ' } },
      { id: 'h22', text: { en: 'Overthinking', fa: 'فکر و خیال زیاد' } },
      { id: 'h23', text: { en: 'Brain freeze', fa: 'یخ‌زدگی مغز' } },
      { id: 'h24', text: { en: 'Goosebumps', fa: 'سیخ شدن مو' } },
      { id: 'h25', text: { en: 'Awkward silence', fa: 'سکوت معذب' } },
      { id: 'h26', text: { en: 'Stage fright', fa: 'استرس روی صحنه' } },
      { id: 'h27', text: { en: 'Food coma', fa: 'خواب بعد از غذا' } },
      { id: 'h28', text: { en: 'Diet starting Monday', fa: 'رژیم از شنبه' } },
      { id: 'h29', text: { en: 'Charging cable at 1%', fa: 'شارژر در یک درصد' } },
      { id: 'h30', text: { en: 'Autocorrect fail', fa: 'سوتی غلط‌گیر خودکار' } },
      { id: 'h31', text: { en: 'Group project', fa: 'کار گروهی' } },
      { id: 'h32', text: { en: 'Alarm snooze', fa: 'اسنوز کردن آلارم' } },
      { id: 'h33', text: { en: 'Traffic jam', fa: 'ترافیک' } },
      { id: 'h34', text: { en: 'Power outage', fa: 'قطع برق' } },
      { id: 'h35', text: { en: 'Mercury retrograde', fa: 'عطارد برگشتی' } },
      { id: 'h36', text: { en: 'Existential crisis', fa: 'بحران وجودی' } },
      { id: 'h37', text: { en: 'Telepathy', fa: 'تله‌پاتی' } },
      { id: 'h38', text: { en: 'Invisible wall', fa: 'دیوار نامرئی' } },
      { id: 'h39', text: { en: 'Slow internet', fa: 'اینترنت کند' } },
      { id: 'h40', text: { en: 'Seen-zoned', fa: 'سین شدن بی‌جواب' } },
      { id: 'h41', text: { en: 'FOMO', fa: 'ترس از جا ماندن' } },
      { id: 'h42', text: { en: 'Adulting', fa: 'ادای بزرگ‌ترها' } },
      { id: 'h43', text: { en: 'Small talk', fa: 'گپ الکی' } },
      { id: 'h44', text: { en: 'Dad joke', fa: 'جوک بی‌مزهٔ باباها' } },
      { id: 'h45', text: { en: 'Plot twist', fa: 'پیچش داستان' } },
      { id: 'h46', text: { en: 'Gym motivation', fa: 'انگیزهٔ باشگاه' } },
      { id: 'h47', text: { en: 'New year resolution', fa: 'قول سال نو' } },
      { id: 'h48', text: { en: 'Sleep paralysis', fa: 'بختک' } },
    ],
  },
  {
    id: 'afterdark',
    words: [
      { id: 'd1', text: { en: 'Lap dance', fa: 'لپ‌دنس' } },
      { id: 'd2', text: { en: 'Striptease', fa: 'رقص استریپ' } },
      { id: 'd3', text: { en: 'First kiss', fa: 'اولین بوسه' } },
      { id: 'd4', text: { en: 'Flirting at the bar', fa: 'لاس زدن تو بار' } },
      { id: 'd5', text: { en: 'Walk of shame', fa: 'برگشتن صبحِ بعد' } },
      { id: 'd6', text: { en: 'Sexy dance', fa: 'رقص سکسی' } },
      { id: 'd7', text: { en: 'Blowing a kiss', fa: 'بوس فرستادن' } },
      { id: 'd8', text: { en: 'Pillow talk', fa: 'حرف‌های رو بالش' } },
      { id: 'd9', text: { en: 'Slow dance', fa: 'رقص آروم دونفره' } },
      { id: 'd10', text: { en: 'Body shot', fa: 'بادی‌شات' } },
      { id: 'd11', text: { en: 'Speed dating', fa: 'قرار سریع' } },
      { id: 'd12', text: { en: 'Honeymoon', fa: 'ماه عسل' } },
      { id: 'd13', text: { en: 'Skinny dipping', fa: 'شنای لخت' } },
      { id: 'd14', text: { en: 'Hickey', fa: 'کبودی گردن' } },
      { id: 'd15', text: { en: 'Seductive wink', fa: 'چشمک اغواگر' } },
      { id: 'd16', text: { en: 'Twerking', fa: 'تورک زدن' } },
      { id: 'd17', text: { en: 'Pole dance', fa: 'رقص میله' } },
      { id: 'd18', text: { en: 'Cold shower', fa: 'دوش آب سرد' } },
      { id: 'd19', text: { en: 'Morning after', fa: 'صبح روز بعد' } },
      { id: 'd20', text: { en: 'Friend zone', fa: 'فرند زون' } },
      { id: 'd21', text: { en: 'Love triangle', fa: 'مثلث عشقی' } },
      { id: 'd22', text: { en: 'Swiping on Tinder', fa: 'سوایپ تو تیندر' } },
      { id: 'd23', text: { en: 'Sliding into DMs', fa: 'رفتن تو دایرکت' } },
      { id: 'd24', text: { en: 'Bachelor party', fa: 'مهمونی مجردی' } },
      { id: 'd25', text: { en: 'Wedding night', fa: 'شب عروسی' } },
      { id: 'd26', text: { en: 'French kiss', fa: 'بوسهٔ فرانسوی' } },
      { id: 'd27', text: { en: 'Cuddling', fa: 'بغل کردن' } },
      { id: 'd28', text: { en: 'Spooning', fa: 'قاشقی خوابیدن' } },
      { id: 'd29', text: { en: 'Sensual massage', fa: 'ماساژ عاشقانه' } },
      { id: 'd30', text: { en: 'Whispering in the ear', fa: 'در گوشی گفتن' } },
      { id: 'd31', text: { en: 'Marriage proposal', fa: 'خواستگاری' } },
      { id: 'd32', text: { en: 'Jealous partner', fa: 'پارتنر حسود' } },
      { id: 'd33', text: { en: 'Caught cheating', fa: 'مچ‌گیری خیانت' } },
      { id: 'd34', text: { en: 'Sexting', fa: 'سکسی چت' } },
      { id: 'd35', text: { en: 'Nude beach', fa: 'ساحل لختی‌ها' } },
      { id: 'd36', text: { en: 'One-night stand', fa: 'رابطهٔ یک‌شبه' } },
      { id: 'd37', text: { en: 'Playing footsie', fa: 'پا بازی زیر میز' } },
      { id: 'd38', text: { en: 'Undressing with your eyes', fa: 'با نگاه قورت دادن' } },
      { id: 'd39', text: { en: 'Strip poker', fa: 'پوکر لباسی' } },
      { id: 'd40', text: { en: 'Seven minutes in heaven', fa: 'هفت دقیقه تو کمد' } },
      { id: 'd41', text: { en: 'Kissing booth', fa: 'دکهٔ بوسه' } },
      { id: 'd42', text: { en: 'Love letter', fa: 'نامهٔ عاشقانه' } },
      { id: 'd43', text: { en: 'Blind date', fa: 'قرار ندیده' } },
      { id: 'd44', text: { en: 'Hot tub party', fa: 'مهمونی جکوزی' } },
      { id: 'd45', text: { en: 'Silk sheets', fa: 'ملافهٔ ابریشمی' } },
      { id: 'd46', text: { en: 'Biting your lip', fa: 'گاز گرفتن لب' } },
      { id: 'd47', text: { en: 'Catwalk strut', fa: 'راه رفتن مانکنی' } },
      { id: 'd48', text: { en: 'Handcuffs', fa: 'دستبند' } },
    ],
  },
]

export function getActWords(packId: string): ActWord[] {
  return ACT_PACKS.find((p) => p.id === packId)?.words ?? ACT_PACKS[0]!.words
}
