import type { Locale } from '../../store/prefs'

export interface WordPack {
  id: string
  /** Stable i18n key suffix: packs.{id} */
  nameKey: string
  words: Record<Locale, string[]>
}

/**
 * Rich bilingual dictionaries for Impostor.
 * Each locale has its own culturally natural set (not 1:1 transliteration).
 * ~60–70 words per pack so 2–3 sessions rarely repeat with freshPick history.
 */
export const WORD_PACKS: WordPack[] = [
  {
    id: 'everyday',
    nameKey: 'everyday',
    words: {
      en: [
        'Coffee',
        'Pizza',
        'Beach',
        'Library',
        'Airport',
        'Gym',
        'Birthday',
        'Camping',
        'Wedding',
        'Subway',
        'Laundry',
        'Zoo',
        'Museum',
        'Hospital',
        'School',
        'Concert',
        'Market',
        'Hotel',
        'Park',
        'Cinema',
        'Toothbrush',
        'Umbrella',
        'Backpack',
        'Alarm clock',
        'Sunglasses',
        'Remote control',
        'Traffic jam',
        'Elevator',
        'Post office',
        'Haircut',
        'Grocery bag',
        'Parking ticket',
        'Coffee shop',
        'Night bus',
        'Power bank',
        'Selfie',
        'Password',
        'Wi-Fi',
        'Headphones',
        'Sneakers',
        'Raincoat',
        'Microwave',
        'Fridge',
        'Balcony',
        'Neighbor',
        'Mailbox',
        'Bus stop',
        'Taxi',
        'Crosswalk',
        'Fire alarm',
        'Vending machine',
        'Laundry day',
        'Monday morning',
        'Nap',
        'Keychain',
        'Wallet',
        'Charger',
        'Notebook',
        'Sticky note',
        'Whiteboard',
        'Office chair',
        'Water bottle',
        'Lunch break',
        'Weekend',
        'Group chat',
      ],
      fa: [
        'قهوه',
        'پیتزا',
        'ساحل',
        'کتابخانه',
        'فرودگاه',
        'باشگاه',
        'تولد',
        'کمپینگ',
        'عروسی',
        'مترو',
        'لباسشویی',
        'باغ‌وحش',
        'موزه',
        'بیمارستان',
        'مدرسه',
        'کنسرت',
        'بازار',
        'هتل',
        'پارک',
        'سینما',
        'مسواک',
        'چتر',
        'کوله‌پشتی',
        'ساعت زنگ‌دار',
        'عینک آفتابی',
        'ریموت کنترل',
        'ترافیک',
        'آسانسور',
        'اداره پست',
        'کوتاهی مو',
        'کیسه خرید',
        'جریمه پارک',
        'کافه‌نت',
        'اتوبوس شب',
        'پاوربانک',
        'سلفی',
        'رمز عبور',
        'وای‌فای',
        'هدفون',
        'کفش ورزشی',
        'بارانی',
        'مایکروویو',
        'یخچال',
        'بالکن',
        'همسایه',
        'صندوق پست',
        'ایستگاه اتوبوس',
        'تاکسی',
        'خط عابر',
        'آژیر آتش',
        'دستگاه فروش',
        'روز رختشویی',
        'صبح دوشنبه',
        'چرت',
        'جاکلیدی',
        'کیف پول',
        'شارژر',
        'دفترچه',
        'یادداشت چسبی',
        'وایت‌برد',
        'صندلی اداری',
        'قمقمه',
        'زنگ ناهار',
        'آخر هفته',
        'گروه چت',
        'نانوایی',
        'سوپرمارکت',
        'داروخانه',
        'آرایشگاه',
        'پمپ بنزین',
      ],
    },
  },
  {
    id: 'food',
    nameKey: 'food',
    words: {
      en: [
        'Sushi',
        'Burger',
        'Taco',
        'Pasta',
        'Ice cream',
        'Ramen',
        'Avocado',
        'Croissant',
        'Barbecue',
        'Smoothie',
        'Donut',
        'Curry',
        'Waffle',
        'Nachos',
        'Bagel',
        'Popcorn',
        'Steak',
        'Mango',
        'Cheese',
        'Chocolate',
        'Pancakes',
        'Garlic bread',
        'Hot dog',
        'Fried chicken',
        'Mac and cheese',
        'Dumplings',
        'Spring rolls',
        'Hummus',
        'Falafel',
        'Olive oil',
        'Peanut butter',
        'Strawberry',
        'Blueberry',
        'Pineapple',
        'Watermelon',
        'Coconut',
        'Lemonade',
        'Milkshake',
        'Espresso',
        'Matcha',
        'Honey',
        'Cinnamon',
        'Chili pepper',
        'Mushroom',
        'Spinach',
        'Corn on the cob',
        'French fries',
        'Onion rings',
        'Cupcake',
        'Brownie',
        'Cheesecake',
        'Tiramisu',
        'Gummy bears',
        'Potato chips',
        'Pretzel',
        'Omelette',
        'Toast',
        'Granola',
        'Yogurt',
        'Salad',
        'Soup',
        'Sandwich',
        'Burrito',
        'Kebab',
        'Paella',
      ],
      fa: [
        'سوشی',
        'برگر',
        'تاکو',
        'پاستا',
        'بستنی',
        'رامن',
        'آووکادو',
        'کروسان',
        'کباب زغالی',
        'اسموتی',
        'دونات',
        'کاری',
        'وافل',
        'ناچو',
        'بِیگل',
        'پاپ‌کرن',
        'استیک',
        'انبه',
        'پنیر',
        'شکلات',
        'پنکیک',
        'نان سیر',
        'هات‌داگ',
        'مرغ سوخاری',
        'ماکارونی پنیری',
        'دمپلینگ',
        'رول بهاری',
        'حمص',
        'فلافل',
        'روغن زیتون',
        'کره بادام‌زمینی',
        'توت‌فرنگی',
        'بلوبری',
        'آناناس',
        'هندوانه',
        'نارگیل',
        'لیموناد',
        'میلک‌شیک',
        'اسپرسو',
        'ماچا',
        'عسل',
        'دارچین',
        'فلفل تند',
        'قارچ',
        'اسفناج',
        'ذرت بو داده',
        'سیب‌زمینی سرخ‌کرده',
        'حلقه پیاز',
        'کاپ‌کیک',
        'براونی',
        'چیزکیک',
        'تیرامیسو',
        'پفک',
        'چیپس',
        'چوب شور',
        'املت',
        'نان تست',
        'گرانولا',
        'ماست',
        'سالاد',
        'سوپ',
        'ساندویچ',
        'بوریتو',
        'کباب',
        'چلوکباب',
        'قورمه‌سبزی',
        'فسنجان',
        'آش رشته',
        'عدسی',
        'کوکو سبزی',
        'نان سنگک',
        'برنج دم‌کشیده',
        'ترشی',
        'دوغ',
        'زعفران',
      ],
    },
  },
  {
    id: 'places',
    nameKey: 'places',
    words: {
      en: [
        'Paris',
        'Tokyo',
        'Desert',
        'Jungle',
        'Castle',
        'Volcano',
        'Island',
        'Skyscraper',
        'Farm',
        'Cave',
        'Stadium',
        'Harbor',
        'Temple',
        'Bridge',
        'Carnival',
        'Observatory',
        'Lighthouse',
        'Marketplace',
        'Underground',
        'Rooftop',
        'Mountain',
        'Waterfall',
        'Glacier',
        'Rainforest',
        'Canyon',
        'Beach hut',
        'Igloo',
        'Pyramid',
        'Palace',
        'Museum wing',
        'Train station',
        'Airport lounge',
        'Amusement park',
        'Zoo enclosure',
        'Botanical garden',
        'City square',
        'Old town',
        'Harbor dock',
        'Ski resort',
        'Campground',
        'National park',
        'Coral reef',
        'Hot spring',
        'Desert oasis',
        'Cliff edge',
        'Riverbank',
        'Meadow',
        'Vineyard',
        'Orchard',
        'Windmill',
        'Clock tower',
        'Subway tunnel',
        'Parking garage',
        'Shopping mall',
        'Food court',
        'Library stacks',
        'University campus',
        'Hospital ward',
        'Film studio',
        'Recording booth',
        'Space museum',
        'Planetarium',
        'Aquarium',
        'Safari lodge',
        'Mountain cabin',
      ],
      fa: [
        'پاریس',
        'توکیو',
        'کویر',
        'جنگل',
        'قلعه',
        'آتشفشان',
        'جزیره',
        'آسمان‌خراش',
        'مزرعه',
        'غار',
        'ورزشگاه',
        'بندر',
        'معبد',
        'پل',
        'کارناوال',
        'رصدخانه',
        'فانوس دریایی',
        'بازارچه',
        'زیرزمین',
        'پشت‌بام',
        'کوه',
        'آبشار',
        'یخچال طبیعی',
        'جنگل بارانی',
        'دره',
        'کلبه ساحلی',
        'ایگلو',
        'اهرام',
        'کاخ',
        'بال موزه',
        'ایستگاه قطار',
        'سالن فرودگاه',
        'شهر بازی',
        'قفس باغ‌وحش',
        'باغ گیاه‌شناسی',
        'میدان شهر',
        'بازار قدیم',
        'اسکله',
        'پیست اسکی',
        'محل کمپ',
        'پارک ملی',
        'صخره مرجانی',
        'چشمه آب گرم',
        'واحه',
        'لبه صخره',
        'کنار رود',
        'چمنزار',
        'تاکستان',
        'باغ میوه',
        'آسیاب بادی',
        'برج ساعت',
        'تونل مترو',
        'پارکینگ طبقاتی',
        'مرکز خرید',
        'فودکورت',
        'قفسه کتابخانه',
        'دانشگاه',
        'بخش بیمارستان',
        'استودیو فیلم',
        'اتاق ضبط',
        'موزه فضا',
        'آسمان‌نما',
        'آکواریوم',
        'کمپ سافاری',
        'کلبه کوهستانی',
        'تهران',
        'اصفهان',
        'شیراز',
        'یزد',
        'شمال ایران',
        'خلیج فارس',
        'دریای خزر',
        'دماوند',
        'بازار تبریز',
        'میدان نقش جهان',
      ],
    },
  },
  {
    id: 'wild',
    nameKey: 'wild',
    words: {
      en: [
        'Time machine',
        'Invisible ink',
        'Robot dog',
        'Magic mirror',
        'Treasure map',
        'Haunted house',
        'Space station',
        'Dragon egg',
        'Secret tunnel',
        'Talking plant',
        'Flying car',
        'Crystal ball',
        'Pirate ship',
        'Underwater city',
        'Shadow clone',
        'Lucky coin',
        'Midnight feast',
        'Echo chamber',
        'Paper airplane',
        'Thunderstorm',
        'Teleport button',
        'Gravity boots',
        'Memory eraser',
        'Dream diary',
        'Ghost Wi-Fi',
        'Candy rain',
        'Giant rubber duck',
        'Laser broom',
        'Pocket volcano',
        'Singing toaster',
        'Cloud elevator',
        'Moon picnic',
        'Invisible backpack',
        'Time-loop alarm',
        'Neon jungle',
        'Bubble spacesuit',
        'Vampire librarian',
        'Detective cat',
        'Rainbow bridge',
        'Ice cream blizzard',
        'Robot orchestra',
        'Secret handshake',
        'Floating island',
        'Portal door',
        'Glow-in-the-dark socks',
        'Whispering library',
        'Chocolate fountain',
        'Storm in a bottle',
        'Mirror maze',
        'Lucky socks',
        'Alien passport',
        'Midnight train',
        'Pixel forest',
        'Thunder drum',
        'Crystal staircase',
        'Balloon army',
        'Sleepwalking map',
        'Firework umbrella',
        'Hologram pet',
        'Sandcastle kingdom',
        'Comet taxi',
        'Puzzle key',
        'Echo headphones',
        'Night market genie',
        'Paper moon',
      ],
      fa: [
        'ماشین زمان',
        'جوهر نامرئی',
        'سگ ربات',
        'آینه جادویی',
        'نقشه گنج',
        'خانه ارواح',
        'ایستگاه فضایی',
        'تخم اژدها',
        'تونل مخفی',
        'گیاه حرف‌زن',
        'ماشین پرنده',
        'گوی بلورین',
        'کشتی دزدان دریایی',
        'شهر زیر آب',
        'همزاد سایه',
        'سکه شانس',
        'ضیافت نیمه‌شب',
        'اتاق پژواک',
        'هواپیمای کاغذی',
        'طوفان رعد و برق',
        'دکمه تلپورت',
        'چکمه گرانش',
        'پاک‌کن حافظه',
        'دفتر رویا',
        'وای‌فای شبح',
        'باران آب‌نبات',
        'اردک لاستیکی غول',
        'جاروی لیزری',
        'آتشفشان جیبی',
        'توستر آوازخوان',
        'آسانسور ابری',
        'پیک‌نیک روی ماه',
        'کوله‌پشتی نامرئی',
        'زنگ حلقه زمان',
        'جنگل نئون',
        'لباس فضایی حبابی',
        'کتابدار خون‌آشام',
        'گربه کارآگاه',
        'پل رنگین‌کمان',
        'کولاک بستنی',
        'ارکستر ربات',
        'دست دادن مخفی',
        'جزیره شناور',
        'درِ پورتال',
        'جوراب شب‌تاب',
        'کتابخانه نجواگر',
        'فواره شکلات',
        'طوفان در بطری',
        'هزارتوی آینه',
        'جوراب شانس',
        'پاسپورت فضایی',
        'قطار نیمه‌شب',
        'جنگل پیکسلی',
        'طبل رعد',
        'پله بلورین',
        'ارتش بادکنک',
        'نقشه خواب‌گردی',
        'چتر آتش‌بازی',
        'حیوان خانگی هولوگرام',
        'پادشاهی قلعه‌شنی',
        'تاکسی دنباله‌دار',
        'کلید پازل',
        'هدفون پژواک',
        'جن بازار شب',
        'ماه کاغذی',
        'فرش پرنده',
        'چراغ جادو',
        'دیو چراغ',
        'کلاه نامرئی',
        'شمشیر نور',
        'جعبه اسرار',
        'ساعت شنی جادویی',
        'نقشه گمشده',
        'کلید آسمان',
      ],
    },
  },
]

export function getPackWords(packId: string, locale: Locale): string[] {
  const pack = WORD_PACKS.find((p) => p.id === packId) ?? WORD_PACKS[0]!
  return pack.words[locale] ?? pack.words.en
}

export function suggestedImpostorCount(playerCount: number) {
  if (playerCount <= 4) return 1
  if (playerCount <= 7) return 1
  if (playerCount <= 10) return 2
  return 3
}
