import type { Locale } from '../../store/prefs'

/**
 * Fuse prompt pools — culturally natural per locale (~250+ each),
 * large enough that several party nights with freshPick rarely repeat.
 */
export const FUSE_PROMPTS: Record<Locale, string[]> = {
  en: [
    'Name a fruit',
    'Say a movie title',
    'Name an animal',
    'Say a city',
    'Name something cold',
    'Say a color',
    'Name a sport',
    'Say a food you hate',
    'Name a superhero',
    'Say a school subject',
    'Name something sticky',
    'Say a car brand',
    'Name a cartoon character',
    'Say something you do every morning',
    'Name a musical instrument',
    'Say a country',
    'Name something you wear',
    'Say a drink',
    'Name a job',
    'Say an app on your phone',
    'Name something in your kitchen',
    'Say a board game',
    'Name a holiday',
    'Say a pizza topping',
    'Name something that flies',
    'Say a social media platform',
    'Name a dessert',
    'Say a brand of sneakers',
    'Name something you find at the beach',
    'Say a TV show',
    'Name a vegetable',
    'Say something that makes noise',
    'Name a planet',
    'Say a type of weather',
    'Name something you take on a trip',
    'Say a childhood toy',
    'Name something spicy',
    'Say a famous landmark',
    'Name a video game',
    'Say something you do before bed',
    'Name a flower',
    'Say a type of cheese',
    'Name something expensive',
    'Say a breakfast food',
    'Name something soft',
    'Say a programming language',
    'Name a sea creature',
    'Say something you Google',
    'Name a tool',
    'Say a snack',
    'Name something round',
    'Say a winter activity',
    'Name a book genre',
    'Say something that smells good',
    'Name a dance style',
    'Say a kitchen appliance',
    'Name something you fear',
    'Say a mode of transport',
    'Name a body part',
    'Say something you collect',
    'Name a tree',
    'Say a comedy movie',
    'Name something you open with a key',
    'Say a summer activity',
    'Name something electric',
    'Say a type of pasta',
    'Name something you share',
    'Say a famous athlete',
    'Name something that melts',
    'Say a phone setting',
    'Name a cereal brand',
    'Say a type of shoe',
    'Name something in a bathroom',
    'Say a fast-food chain',
    'Name a bird',
    'Say something you do on a rainy day',
    'Name a board game piece',
    'Say a type of soup',
    'Name something yellow',
    'Say a famous singer',
    'Name a piece of furniture',
    'Say something you find in a park',
    'Name a type of bread',
    'Say a movie villain',
    'Name something that floats',
    'Say a language',
    'Name a kitchen utensil',
    'Say something you wear in winter',
    'Name a candy',
    'Say a type of music',
    'Name something in your backpack',
    'Say a famous painting',
    'Name a wild animal',
    'Say something you do at the gym',
    'Name a type of sandwich',
    'Say a city nickname',
    'Name something shiny',
    'Say a Disney character',
    'Name a type of hat',
    'Say something you buy at a drugstore',
    'Name a river',
    'Say a type of cookie',
    'Name something that buzzes',
    'Say a school club',
    'Name a type of juice',
    'Say something you forget easily',
    'Name a famous scientist',
    'Say a type of salad',
    'Name something red',
    'Say a dating app',
    'Name a type of fish',
    'Say something you do on vacation',
    'Name a board sport',
    'Say a type of tea',
    'Name something in a garage',
    'Say a famous author',
    'Name a type of cake',
    'Say something you charge',
    'Name a mythical creature',
    'Say a type of sauce',
    'Name something you find under a bed',
    'Say a comedy TV show',
    'Name a type of nut',
    'Say something that stretches',
    'Name a mountain',
    'Say a type of ice cream',
    'Name something you whisper',
    'Say a famous inventor',
    'Name a type of berry',
    'Say something you do when bored',
    'Name a kitchen spice',
    'Say a type of jacket',
    'Name something blue',
    'Say a streaming service',
    'Name a type of bean',
    'Say something you pack for camping',
    'Name a famous building',
    'Say a type of noodle',
    'Name something that squeaks',
    'Say a childhood game',
    'Name a type of soup cracker',
    'Say something you do after work',
    'Name a farm animal',
    'Say a type of soda',
    'Name something you lose often',
    'Name a famous actor',
    'Say a type of pie',
    'Name something green',
    'Say a messaging app',
    'Name a type of mushroom',
    'Say something you find in a hotel',
    'Name a water sport',
    'Say a type of chocolate',
    'Name something that glows',
    'Say a school supply',
    'Name a type of yogurt',
    'Say something you do on Sunday',
    'Name a jungle animal',
    'Say a type of coffee drink',
    'Name something you keep in a drawer',
    'Name a famous athlete’s sport',
    'Say a type of cracker',
    'Name something orange',
    'Say a news website',
    'Name a type of onion',
    'Say something you do at a wedding',
    'Name a winter sport',
    'Say a type of jam',
    'Name something that rolls',
    'Say a lullaby or kids song',
    'Name a type of pickle',
    'Say something you apologize for',
    'Name a desert animal',
    'Say a type of milk',
    'Name something purple',
    'Say a photo filter',
    'Name a type of rice dish',
    'Say something you find at a fair',
    'Name a team sport',
    'Say a type of burrito filling',
    'Name something that drips',
    'Say a password tip',
    'Name a type of leaf',
    'Say something you do when nervous',
    'Name a pet',
    'Say a type of smoothie flavor',
    'Name something black',
    'Say a video call app',
    'Name a type of salad dressing',
    'Say something you buy on sale',
    'Name an Olympic sport',
    'Say a type of chip flavor',
    'Name something that cracks',
    'Say a bedtime routine step',
    'Name a type of herb',
    'Say something you celebrate',
    'Name a zoo animal',
    'Say a type of toast topping',
    'Name something pink',
    'Say a map app',
    'Name a type of taco filling',
    'Say something you find in a car',
    'Name a racket sport',
    'Say a type of cookie dough',
    'Name something that hops',
    'Say a childhood fear',
    'Name a type of cereal topping',
    'Say something you do at midnight',
    'Name an insect',
    'Say a type of soup noodle',
    'Name something white',
    'Say a music app',
    'Name a type of grilled food',
    'Say something you keep on a nightstand',
    'Name a martial art',
    'Say a type of fruit juice',
    'Name something that spins',
    'Say a lucky charm',
    'Name a type of dumpling',
    'Say something you regret buying',
    'Name a sea mammal',
    'Say a type of hot sauce',
    'Name something gold',
    'Say a calendar reminder',
    'Name a type of pasta sauce',
    'Say something you find in a classroom',
    'Name a track and field event',
    'Say a type of sandwich bread',
    'Name something that squeals',
    'Say a New Year tradition',
    'Name a type of frozen dessert',
    'Say something you do in an elevator',
    'Name a reptile',
    'Say a type of bubble tea',
    'Name something silver',
    'Say a weather app feature',
    'Name a type of BBQ food',
    'Say something you find at a party',
    'Name a water animal',
    'Say a type of breakfast pastry',
    'Name something that leaks',
    'Say a weekend plan',
    'Name a type of street food',
    'Say something you whisper to a friend',
    'Name a dinosaur',
    'Say a type of iced drink',
    'Name something brown',
    'Say a fitness app',
    'Name a type of grilled cheese add-in',
    'Say something you keep in a purse',
    'Name a skating sport',
    'Say a type of energy drink',
    'Name something that snaps',
    'Say a birthday gift idea',
    'Name a type of pizza crust',
    'Say something you do when you wake up late',
    'Name a farm bird',
    'Say a type of milkshake',
    'Name something gray',
    'Say a shopping app',
    'Name a type of sushi roll',
    'Say something you find in a suitcase',
    'Name a climbing sport',
    'Say a type of popcorn topping',
    'Name something that flickers',
    'Say a travel souvenir',
    'Name a type of wrap filling',
    'Say something you never lend',
    'Name a breakfast cereal',
    'Name something in a toolbox',
    'Say a rainy-day activity',
    'Name a board game expansion vibe',
    'Say a famous river',
    'Name something you recycle',
    'Name a cartoon villain',
    'Say something you do on a plane',
    'Name a kitchen smell',
    'Say a type of pasta shape',
    'Name something in a first-aid kit',
    'Say a famous mountain range',
    'Name a weekend chore',
    'Say a type of salad green',
    'Name something you whisper in a library',
    'Say a childhood nickname style',
    'Name a type of soup bowl food',
    'Say something you find in a glove box',
    'Say a type of weather alert',
    'Name something you pack for the beach',
    'Say a pizza chain',
    'Name a type of cheese texture',
    'Say something you do when the Wi-Fi dies',
    'Name a musical genre',
    'Say a type of camera shot',
    'Name something sticky in the kitchen',
    'Say a famous bridge',
    'Name a type of tea leaf drink',
    'Say something you lose in a sofa',
    'Name a winter coat brand vibe',
    'Say a type of dumpling filling',
    'Name something electric in a car',
    'Say a famous composer',
    'Name a type of yogurt flavor',
    'Say something you do at sunrise',
    'Name a gardening tool',
    'Say a type of chocolate bar',
    'Name something you find in a desk drawer',
    'Say a famous painting style',
    'Name a type of ice cream topping',
    'Say something you Google at 2am',
    'Name a camping essential',
    'Say a type of bread roll',
    'Name something that buzzes in summer',
    'Say a famous castle',
    'Name a type of fruit smoothie',
    'Say something you do before a date',
    'Name a school supply that breaks',
    'Say a type of hot drink',
    'Name something soft in a bedroom',
    'Say a famous lake',
    'Name a type of street snack',
    'Say something you charge overnight',
    'Name a fairy-tale character',
    'Say a type of pancake topping',
    'Name something round in sports',
    'Name a type of sandwich filling',
    'Say something you find at a flea market',
    'Name a dance move',
    'Say a type of soda flavor',
    'Name something you open with scissors',
    'Say a famous waterfall',
    'Name a type of pizza crust style',
    'Say something you do in a waiting room',
    'Name a pet accessory',
    'Name something shiny in a jewelry box',
    'Say a famous desert',
    'Name a type of noodle dish',
    'Say something you pack in a gym bag',
    'Name a horror movie trope',
    'Say a type of milk alternative',
    'Name something you find on a balcony',
    'Say a famous canyon',
    'Name a type of burrito add-on',
    'Say something you do when stuck in traffic',
    'Name a phone accessory',
    'Say a type of cake frosting',
    'Name something cold in a freezer',
    'Say a famous island',
    'Name a type of grilled vegetable',
    'Say something you whisper on a call',
    'Name a board game win condition vibe',
    'Say a type of juice blend',
    'Name something you find in a hotel bathroom',
    'Say a famous volcano',
    'Name a type of sushi topping',
    'Say something you do on a snow day',
    'Name a kitchen gadget',
    'Say a type of cookie filling',
    'Name something that melts in summer',
    'Say a famous forest',
    'Name a type of taco salsa',
    'Say something you keep in a sock drawer',
    'Name a rom-com setting',
    'Say a type of iced coffee',
    'Name something you find at a hardware store',
    'Say a famous bay',
    'Name a type of pasta bake',
    'Say something you do after a haircut',
    'Name a travel pillow item',
    'Say a type of fruit salad fruit',
    'Name something electric in a kitchen',
    'Say a famous tower',
    'Name a type of sandwich sauce',
    'Say something you do when you miss a bus',
    'Name a living room object',
    'Say a type of chocolate dessert',
    'Name something soft for a baby',
    'Say a famous peninsula',
    'Name a type of rice bowl topping',
    'Say something you pack for a sleepover',
    'Name a mystery novel clue vibe',
    'Say a type of sparkling water flavor',
    'Name something you find in a garage fridge',
    'Say a famous archipelago',
    'Name a type of breakfast burrito filling',
    'Say something you do when your phone is at 1%',
    'Name a bathroom product',
    'Say a type of pie filling',
    'Name something round on a pizza',
    'Say a famous national park vibe',
    'Name a type of ramen topping',
    'Say something you do on the first day of school',
    'Name a car interior object',
    'Say a type of milkshake mix-in',
    'Name something sticky at a kids party',
    'Say a famous lighthouse',
    'Name a type of wrap sauce',
    'Say something you do when you hear thunder',
    'Name a desk snack',
    'Say a type of frozen yogurt topping',
    'Name something you find in a picnic basket',
    'Name a famous marketplace',
    'Name a type of egg breakfast',
    'Say something you do before sending a risky text',
    'Name a rainy umbrella moment',
    'Say a type of chip dip',
    'Name something electric that fits in a pocket',
    'Say a famous aquarium fish',
    'Name a type of soup garnish',
    'Say something you do when the power goes out',
    'Name a closet item you forgot you owned',
    'Say a type of burger topping',
    'Name something soft you hug',
    'Say a famous rooftop view',
    'Name a type of toast spread',
    'Say something you do at the end of a movie',
    'Name a wallet item',
    'Say a type of cocktail mocktail vibe',
    'Name something you find under couch cushions',
    'Say a famous street food city vibe',
    'Name a type of cookie dough add-in',
    'Say something you do when you wake from a weird dream',
    'Name a country you want to visit',
    'Say a word that rhymes with "night"',
    'Name a famous painting',
    'Say something that glows in the dark',
    'Name a type of pasta',
    'Say a reason to be late',
    'Name a thing on a keyboard',
    'Say a type of weather',
    'Name a fictional planet',
    'Say something you keep in your wallet',
    'Name a card game',
    'Say a body of water',
    'Name a spice',
    'Say a famous inventor',
    'Name something you recycle',
    'Say a type of tree',
    'Name a video game character',
    'Say something that comes in pairs',
    'Name a genre of music',
    'Say a thing you plug in',
    'Name an Olympic sport',
    'Say a nickname for money',
    'Name something in a first-aid kit',
    'Say a type of dance',
    'Name a planet or moon',
    'Say something you do at a wedding',
    'Name a currency',
    'Say a household chore',
    'Name a type of bread',
    'Say something you find in a garage',
    'Name a famous river',
    'Say a reason to smile',
    'Name a thing with wheels'
  ],
  fa: [
    'یک میوه بگو',
    'اسم یک فیلم بگو',
    'یک حیوان بگو',
    'اسم یک شهر بگو',
    'چیزی سرد بگو',
    'یک رنگ بگو',
    'یک ورزش بگو',
    'غذایی که دوست نداری بگو',
    'یک ابرقهرمان بگو',
    'یک درس مدرسه بگو',
    'چیزی چسبناک بگو',
    'یک برند ماشین بگو',
    'یک شخصیت کارتونی بگو',
    'کاری که هر صبح می‌کنی بگو',
    'یک ساز موسیقی بگو',
    'اسم یک کشور بگو',
    'چیزی که می‌پوشی بگو',
    'یک نوشیدنی بگو',
    'یک شغل بگو',
    'یک اپ گوشی بگو',
    'چیزی توی آشپزخانه بگو',
    'یک بازی فکری بگو',
    'یک مناسبت بگو',
    'یک تاپینگ پیتزا بگو',
    'چیزی که پرواز می‌کند بگو',
    'یک شبکه اجتماعی بگو',
    'یک دسر بگو',
    'یک برند کفش بگو',
    'چیزی که لب ساحل پیدا می‌شود بگو',
    'یک سریال بگو',
    'یک سبزی بگو',
    'چیزی که صدا می‌دهد بگو',
    'یک سیاره بگو',
    'یک جور هوا بگو',
    'چیزی که برای سفر برمی‌داری بگو',
    'یک اسباب‌بازی بچگی بگو',
    'چیزی تند بگو',
    'یک بنای معروف بگو',
    'یک بازی ویدیویی بگو',
    'کاری که قبل خواب می‌کنی بگو',
    'یک گل بگو',
    'یک نوع پنیر بگو',
    'چیزی گران بگو',
    'یک صبحانه بگو',
    'چیزی نرم بگو',
    'یک زبان برنامه‌نویسی بگو',
    'یک موجود دریایی بگو',
    'چیزی که گوگل می‌کنی بگو',
    'یک ابزار بگو',
    'یک تنقلات بگو',
    'چیزی گرد بگو',
    'یک فعالیت زمستانی بگو',
    'یک ژانر کتاب بگو',
    'چیزی خوشبو بگو',
    'یک سبک رقص بگو',
    'یک وسیله آشپزخانه بگو',
    'چیزی که ازش می‌ترسی بگو',
    'یک وسیله نقلیه بگو',
    'یک قسمت بدن بگو',
    'چیزی که جمع می‌کنی بگو',
    'یک درخت بگو',
    'یک فیلم کمدی بگو',
    'چیزی که با کلید باز می‌شود بگو',
    'یک فعالیت تابستانی بگو',
    'چیزی برقی بگو',
    'یک نوع پاستا بگو',
    'چیزی که با کسی شریک می‌شوی بگو',
    'یک ورزشکار معروف بگو',
    'چیزی که آب می‌شود بگو',
    'یک تنظیمات گوشی بگو',
    'یک غذای ایرانی بگو',
    'یک شاعر بگو',
    'یک تیم فوتبال بگو',
    'چیزی توی یخچال بگو',
    'یک شهر شمالی بگو',
    'یک میان‌وعده بگو',
    'چیزی که تو جیب می‌گذاری بگو',
    'یک برنامه تلویزیونی بگو',
    'چیزی که برای مهمانی می‌خری بگو',
    'یک جمله روزمره بگو',
    'یک برند لباس بگو',
    'چیزی زرد بگو',
    'یک خواننده معروف بگو',
    'یک وسیله خانه بگو',
    'چیزی که تو پارک پیدا می‌شود بگو',
    'یک نوع نان بگو',
    'یک شخصیت منفی فیلم بگو',
    'چیزی که روی آب می‌ماند بگو',
    'یک زبان بگو',
    'یک وسیله آشپزی بگو',
    'چیزی که زمستان می‌پوشی بگو',
    'یک شیرینی بگو',
    'یک سبک موسیقی بگو',
    'چیزی توی کوله‌پشتی بگو',
    'یک نقاشی معروف بگو',
    'یک حیوان وحشی بگو',
    'کاری که تو باشگاه می‌کنی بگو',
    'یک نوع ساندویچ بگو',
    'چیزی براق بگو',
    'یک شخصیت دیزنی بگو',
    'یک نوع کلاه بگو',
    'چیزی که از داروخانه می‌خری بگو',
    'یک رودخانه بگو',
    'یک نوع بیسکویت بگو',
    'چیزی که وزوز می‌کند بگو',
    'یک باشگاه مدرسه بگو',
    'یک نوع آبمیوه بگو',
    'چیزی که زود فراموش می‌کنی بگو',
    'یک دانشمند معروف بگو',
    'یک نوع سالاد بگو',
    'چیزی قرمز بگو',
    'یک اپ دوستیابی بگو',
    'یک نوع ماهی بگو',
    'کاری که تو سفر می‌کنی بگو',
    'یک ورزش روی تخته بگو',
    'یک نوع چای بگو',
    'چیزی توی گاراژ بگو',
    'یک نویسنده معروف بگو',
    'یک نوع کیک بگو',
    'چیزی که شارژ می‌کنی بگو',
    'یک موجود افسانه‌ای بگو',
    'یک نوع سس بگو',
    'چیزی که زیر تخت پیدا می‌شود بگو',
    'یک سریال کمدی بگو',
    'یک نوع آجیل بگو',
    'چیزی که کش می‌آید بگو',
    'یک کوه بگو',
    'یک نوع بستنی بگو',
    'چیزی که نجوا می‌کنی بگو',
    'یک مخترع معروف بگو',
    'یک نوع توت بگو',
    'کاری که وقتی حوصله‌ات سر می‌رود بگو',
    'یک ادویه بگو',
    'یک نوع کاپشن بگو',
    'چیزی آبی بگو',
    'یک سرویس استریم بگو',
    'یک نوع لوبیا بگو',
    'چیزی که برای کمپ برمی‌داری بگو',
    'یک ساختمان معروف بگو',
    'یک نوع رشته بگو',
    'چیزی که جیرجیر می‌کند بگو',
    'یک بازی بچگی بگو',
    'کاری که بعد از کار می‌کنی بگو',
    'یک حیوان مزرعه بگو',
    'یک نوع نوشابه بگو',
    'چیزی که زیاد گم می‌کنی بگو',
    'یک بازیگر معروف بگو',
    'یک نوع پای بگو',
    'چیزی سبز بگو',
    'یک اپ پیام‌رسان بگو',
    'یک نوع قارچ بگو',
    'چیزی که تو هتل پیدا می‌شود بگو',
    'یک ورزش آبی بگو',
    'یک نوع شکلات بگو',
    'چیزی که نور می‌دهد بگو',
    'یک وسیله مدرسه بگو',
    'یک نوع ماست بگو',
    'کاری که یکشنبه می‌کنی بگو',
    'یک حیوان جنگل بگو',
    'یک نوع قهوه بگو',
    'چیزی که تو کشو می‌گذاری بگو',
    'یک ورزش معروف بگو',
    'چیزی نارنجی بگو',
    'یک سایت خبری بگو',
    'یک نوع پیاز بگو',
    'کاری که تو عروسی می‌کنی بگو',
    'یک ورزش زمستانی بگو',
    'یک نوع مربا بگو',
    'چیزی که غلت می‌خورد بگو',
    'یک لالایی بگو',
    'یک نوع ترشی بگو',
    'چیزی که بابت آن عذرخواهی می‌کنی بگو',
    'یک حیوان کویر بگو',
    'یک نوع شیر بگو',
    'چیزی بنفش بگو',
    'یک فیلتر عکس بگو',
    'یک نوع پلو بگو',
    'چیزی که تو شهربازی پیدا می‌شود بگو',
    'یک ورزش تیمی بگو',
    'یک محتویات بوریتو بگو',
    'چیزی که چکه می‌کند بگو',
    'یک نکته رمز عبور بگو',
    'یک نوع برگ بگو',
    'کاری که وقتی استرس داری بگو',
    'یک حیوان خانگی بگو',
    'یک طعم اسموتی بگو',
    'چیزی سیاه بگو',
    'یک اپ تماس تصویری بگو',
    'یک نوع سس سالاد بگو',
    'چیزی که حراج می‌خری بگو',
    'یک ورزش المپیک بگو',
    'یک طعم چیپس بگو',
    'چیزی که ترک می‌خورد بگو',
    'یک عادت قبل خواب بگو',
    'یک نوع گیاه معطر بگو',
    'چیزی که جشن می‌گیری بگو',
    'یک حیوان باغ‌وحش بگو',
    'یک چیز روی نان تست بگو',
    'چیزی صورتی بگو',
    'یک اپ نقشه بگو',
    'یک محتویات تاکو بگو',
    'چیزی که تو ماشین پیدا می‌شود بگو',
    'یک ورزش راکتی بگو',
    'یک نوع خمیر کوکی بگو',
    'چیزی که می‌پرد بگو',
    'یک ترس بچگی بگو',
    'یک چیز روی غلات بگو',
    'کاری که نیمه‌شب می‌کنی بگو',
    'یک حشره بگو',
    'یک نوع رشته سوپ بگو',
    'چیزی سفید بگو',
    'یک اپ موسیقی بگو',
    'یک غذای کبابی بگو',
    'چیزی که کنار تخت می‌گذاری بگو',
    'یک هنر رزمی بگو',
    'چیزی که می‌چرخد بگو',
    'یک شانس‌آورد بگو',
    'یک نوع دمپلینگ بگو',
    'چیزی که پشیمان شدی خریدی بگو',
    'یک پستاندار دریایی بگو',
    'یک نوع سس تند بگو',
    'چیزی طلایی بگو',
    'یک یادآوری تقویم بگو',
    'یک نوع سس پاستا بگو',
    'چیزی که تو کلاس پیدا می‌شود بگو',
    'یک رشته دو و میدانی بگو',
    'یک نوع نان ساندویچ بگو',
    'چیزی که جیغ می‌کشد بگو',
    'یک رسم سال نو بگو',
    'یک دسر یخ‌زده بگو',
    'کاری که تو آسانسور می‌کنی بگو',
    'یک خزنده بگو',
    'یک نوع بابل تی بگو',
    'چیزی نقره‌ای بگو',
    'یک قابلیت اپ هوا بگو',
    'یک غذای باربیکیو بگو',
    'چیزی که تو مهمانی پیدا می‌شود بگو',
    'یک حیوان آبزی بگو',
    'یک شیرینی صبحانه بگو',
    'چیزی که نشتی دارد بگو',
    'یک برنامه آخر هفته بگو',
    'یک غذای خیابانی بگو',
    'چیزی که به دوستت نجوا می‌کنی بگو',
    'یک دایناسور بگو',
    'یک نوشیدنی یخ‌زده بگو',
    'چیزی قهوه‌ای بگو',
    'یک اپ تناسب اندام بگو',
    'یک چیز داخل پنیر تست بگو',
    'چیزی که تو کیف دستی می‌گذاری بگو',
    'یک ورزش اسکیت بگو',
    'یک نوشیدنی انرژی‌زا بگو',
    'چیزی که می‌شکند بگو',
    'یک هدیه تولد بگو',
    'یک نوع خمیر پیتزا بگو',
    'کاری که وقتی دیر بیدار می‌شوی بگو',
    'یک پرنده مزرعه بگو',
    'یک نوع میلک‌شیک بگو',
    'چیزی خاکستری بگو',
    'یک اپ خرید بگو',
    'یک نوع سوشی بگو',
    'چیزی که تو چمدان پیدا می‌شود بگو',
    'یک ورزش سنگ‌نوردی بگو',
    'یک تاپینگ پاپ‌کرن بگو',
    'چیزی که چشمک می‌زند بگو',
    'یک سوغاتی سفر بگو',
    'یک محتویات رپ بگو',
    'چیزی که هیچ‌وقت قرض نمی‌دهی بگو',
    'یک شهر جنوبی بگو',
    'یک تیم والیبال بگو',
    'چیزی توی کیف مدرسه بگو',
    'یک ضرب‌المثل بگو',
    'یک خوراکی شب‌چره بگو',
    'چیزی که تو مترو می‌بینی بگو',
    'یک برند گوشی بگو',
    'یک نوع کباب بگو',
    'چیزی که برای مهمان می‌آوری بگو',
    'یک رسم ایرانی بگو',
    'یک نوع دوغ بگو',
    'چیزی که تو بازار می‌خری بگو',
    'یک شاعر کلاسیک بگو',
    'یک خوراکی نوروز بگو',
    'چیزی که تو تاکسی گم می‌شود بگو',
    'یک تیم بسکتبال بگو',
    'یک نوع آش بگو',
    'چیزی که تو ییلاق برمی‌داری بگو',
    'یک غلات صبحانه بگو',
    'یک نوع کلوچه بگو',
    'چیزی توی جعبه‌ابزار بگو',
    'یک کار روز بارانی بگو',
    'یک رودخانه معروف بگو',
    'چیزی که بازیافت می‌کنی بگو',
    'یک ضدقهرمان کارتونی بگو',
    'کاری که تو هواپیما می‌کنی بگو',
    'یک بوی آشپزخانه بگو',
    'یک شکل پاستا بگو',
    'چیزی توی جعبه کمک‌های اولیه بگو',
    'یک رشته کوه معروف بگو',
    'یک کار آخر هفته بگو',
    'یک برگ سالاد بگو',
    'چیزی که تو کتابخانه نجوا می‌کنی بگو',
    'یک لقبی بچگی بگو',
    'یک غذای کاسه‌ای بگو',
    'چیزی توی داشبورد ماشین بگو',
    'یک هشدار هوا بگو',
    'چیزی که برای ساحل برمی‌داری بگو',
    'یک زنجیره پیتزا بگو',
    'کاری که وقتی وای‌فای قطع می‌شود بگو',
    'یک ژانر موسیقی بگو',
    'یک نوع شات دوربین بگو',
    'چیزی چسبناک تو آشپزخانه بگو',
    'یک پل معروف بگو',
    'چیزی که تو مبل گم می‌شود بگو',
    'یک نوع فیلینگ دمپلینگ بگو',
    'چیزی برقی تو ماشین بگو',
    'یک آهنگساز معروف بگو',
    'یک طعم ماست بگو',
    'کاری که طلوع آفتاب می‌کنی بگو',
    'یک ابزار باغبانی بگو',
    'یک شکلات تخته‌ای بگو',
    'چیزی توی کشوی میز بگو',
    'یک سبک نقاشی بگو',
    'یک تاپینگ بستنی بگو',
    'چیزی که ساعت دو شب گوگل می‌کنی بگو',
    'یک وسیله ضروری کمپ بگو',
    'یک نوع نان رول بگو',
    'چیزی که تابستان وزوز می‌کند بگو',
    'یک قلعه معروف بگو',
    'یک اسموتی میوه‌ای بگو',
    'کاری که قبل قرار می‌کنی بگو',
    'یک وسیله مدرسه که می‌شکند بگو',
    'یک نوشیدنی گرم بگو',
    'چیزی نرم تو اتاق خواب بگو',
    'یک دریاچه معروف بگو',
    'یک خوراکی خیابانی بگو',
    'چیزی که شب شارژ می‌کنی بگو',
    'یک شخصیت افسانه‌ای بگو',
    'یک تاپینگ پنکیک بگو',
    'چیزی گرد تو ورزش بگو',
    'یک محتویات ساندویچ بگو',
    'چیزی که تو بازار جمعه پیدا می‌شود بگو',
    'یک حرکت رقص بگو',
    'یک طعم نوشابه بگو',
    'چیزی که با قیچی باز می‌کنی بگو',
    'یک آبشار معروف بگو',
    'کاری که تو اتاق انتظار می‌کنی بگو',
    'یک وسیله حیوان خانگی بگو',
    'چیزی براق تو جعبه جواهر بگو',
    'یک کویر معروف بگو',
    'یک غذای رشته‌ای بگو',
    'چیزی که تو کیف باشگاه می‌گذاری بگو',
    'یک کلیشه فیلم ترسناک بگو',
    'یک جایگزین شیر بگو',
    'چیزی که تو بالکن پیدا می‌شود بگو',
    'یک دره معروف بگو',
    'یک افزودنی بوریتو بگو',
    'کاری که تو ترافیک می‌کنی بگو',
    'یک لوازم جانبی گوشی بگو',
    'یک نوع خامه کیک بگو',
    'چیزی سرد تو فریزر بگو',
    'یک جزیره معروف بگو',
    'یک سبزی کبابی بگو',
    'چیزی که تو تماس نجوا می‌کنی بگو',
    'یک طعم آبمیوه بگو',
    'چیزی تو حمام هتل بگو',
    'یک آتشفشان معروف بگو',
    'یک تاپینگ سوشی بگو',
    'کاری که روز برفی می‌کنی بگو',
    'یک گجت آشپزخانه بگو',
    'یک فیلینگ کلوچه بگو',
    'چیزی که تابستان آب می‌شود بگو',
    'یک جنگل معروف بگو',
    'یک سس تاکو بگو',
    'چیزی که تو کشوی جوراب می‌گذاری بگو',
    'یک صحنه فیلم عاشقانه بگو',
    'یک قهوه یخ‌زده بگو',
    'چیزی تو فروشگاه ابزار بگو',
    'یک خلیج معروف بگو',
    'یک پاستای فر بگو',
    'کاری که بعد کوتاهی مو می‌کنی بگو',
    'یک وسیله سفر بگو',
    'یک میوه سالاد میوه بگو',
    'چیزی برقی تو آشپزخانه بگو',
    'یک برج معروف بگو',
    'یک سس ساندویچ بگو',
    'کاری که وقتی اتوبوس را از دست می‌دهی بگو',
    'یک وسیله اتاق نشیمن بگو',
    'یک دسر شکلاتی بگو',
    'چیزی نرم برای بچه بگو',
    'یک شبه جزیره معروف بگو',
    'یک تاپینگ کاسه برنج بگو',
    'چیزی که برای خواب‌مهمانی برمی‌داری بگو',
    'یک طعم آب گازدار بگو',
    'چیزی تو یخچال گاراژ بگو',
    'یک مجمع‌الجزایر معروف بگو',
    'یک محتویات بوریتو صبحانه بگو',
    'کاری که وقتی شارژ گوشی ۱٪ است بگو',
    'یک محصول حمام بگو',
    'یک فیلینگ پای بگو',
    'چیزی گرد روی پیتزا بگو',
    'یک حس پارک ملی بگو',
    'یک تاپینگ رامن بگو',
    'کاری که روز اول مدرسه می‌کنی بگو',
    'یک وسیله داخل ماشین بگو',
    'یک افزودنی میلک‌شیک بگو',
    'چیزی چسبناک تو مهمانی بچه بگو',
    'یک فانوس دریایی معروف بگو',
    'یک سس رپ بگو',
    'کاری که وقتی رعد می‌شنوی بگو',
    'یک تنقلات روی میز بگو',
    'یک تاپینگ ماست یخ‌زده بگو',
    'چیزی تو سبد پیک‌نیک بگو',
    'یک بازار معروف بگو',
    'یک صبحانه تخم‌مرغی بگو',
    'کاری که قبل فرستادن پیام ریسکی می‌کنی بگو',
    'یک لحظه چتر بارانی بگو',
    'یک دیپ چیپس بگو',
    'چیزی برقی که تو جیب جا می‌شود بگو',
    'یک ماهی آکواریوم معروف بگو',
    'یک تزئین سوپ بگو',
    'کاری که وقتی برق می‌رود بگو',
    'یک چیز فراموش‌شده تو کمد بگو',
    'یک تاپینگ برگر بگو',
    'چیزی نرم که بغل می‌کنی بگو',
    'یک منظره پشت‌بام معروف بگو',
    'یک کرم روی نان تست بگو',
    'کاری که آخر فیلم می‌کنی بگو',
    'یک چیز تو کیف پول بگو',
    'یک حس موکتل بگو',
    'چیزی زیر کوسن مبل بگو',
    'یک حس شهر غذای خیابانی بگو',
    'یک افزودنی خمیر کوکی بگو',
    'کاری که بعد خواب دیدن عجیب می‌کنی بگو',
    'یک تیم والیبال ایرانی بگو',
    'یک خوراکی سینما بگو',
    'چیزی که تو تاکسی جا می‌ماند بگو',
    'یک برنامه رادیویی بگو',
    'یک نوع آش ایرانی بگو',
    'چیزی که برای شب یلدا می‌خری بگو',
    'یک تیم کشتی بگو',
    'یک خوراکی بین‌راهی بگو',
    'چیزی که تو مترو تهران می‌بینی بگو',
    'یک رسم عید بگو',
    'یک نوع کباب محلی بگو',
    'چیزی که برای مهمانی عصرانه می‌آوری بگو',
    'یک کشوری که دوست داری بروی بگو',
    'یک شهر توریستی ایران بگو',
    'یک نقاشی معروف بگو',
    'چیزی که تو تاریکی می‌درخشد بگو',
    'یک نوع آش یا سوپ بگو',
    'یک بهانه برای دیر رسیدن بگو',
    'یک دکمه روی کیبورد بگو',
    'یک نوع آب‌وهوا بگو',
    'یک شخصیت کارتونی بگو',
    'چیزی که تو کیف پولت نگه می‌داری بگو',
    'یک بازی با ورق بگو',
    'یک دریا یا دریاچه بگو',
    'یک ادویه بگو',
    'یک دانشمند معروف بگو',
    'چیزی که بازیافت می‌کنی بگو',
    'یک نوع درخت بگو',
    'یک شخصیت بازی ویدیویی بگو',
    'چیزی که جفتی می‌آید بگو',
    'یک سبک موسیقی بگو',
    'چیزی که به برق می‌زنی بگو',
    'یک رشتهٔ ورزشی المپیک بگو',
    'یک اسم خودمانی برای پول بگو',
    'چیزی که تو جعبهٔ کمک‌های اولیه هست بگو',
    'یک نوع رقص بگو',
    'یک سیاره یا ماه بگو',
    'کاری که سر عروسی می‌کنی بگو',
    'یک واحد پول بگو',
    'یک کار خانه بگو',
    'یک نوع نان بگو',
    'چیزی که تو پارکینگ پیدا می‌شود بگو',
    'یک رودخانهٔ معروف بگو',
    'یک دلیل برای لبخند بگو',
    'چیزی که چرخ دارد بگو'
  ],
}

export function getFusePrompts(locale: Locale): string[] {
  return FUSE_PROMPTS[locale] ?? FUSE_PROMPTS.en
}

export function suggestedLives(playerCount: number) {
  if (playerCount <= 3) return 3
  if (playerCount <= 6) return 2
  return 2
}
