import type { Locale } from '../../store/prefs'

/**
 * Fuse prompt pools — culturally natural per locale, large enough
 * that a few rounds with freshPick rarely repeat.
 */
export const FUSE_PROMPTS: Record<Locale, string[]> = {
  en: [
    'Name a fruit',
    'Say a movie title',
    'Name an animal',
    'Say a city',
    'Name something cold',
    'Say a color',
    'Name a sport',
    'Say a food you hate',
    'Name a superhero',
    'Say a school subject',
    'Name something sticky',
    'Say a car brand',
    'Name a cartoon character',
    'Say something you do every morning',
    'Name a musical instrument',
    'Say a country',
    'Name something you wear',
    'Say a drink',
    'Name a job',
    'Say an app on your phone',
    'Name something in your kitchen',
    'Say a board game',
    'Name a holiday',
    'Say a pizza topping',
    'Name something that flies',
    'Say a social media platform',
    'Name a dessert',
    'Say a brand of sneakers',
    'Name something you find at the beach',
    'Say a TV show',
    'Name a vegetable',
    'Say something that makes noise',
    'Name a planet',
    'Say a type of weather',
    'Name something you take on a trip',
    'Say a childhood toy',
    'Name something spicy',
    'Say a famous landmark',
    'Name a video game',
    'Say something you do before bed',
    'Name a flower',
    'Say a type of cheese',
    'Name something expensive',
    'Say a breakfast food',
    'Name something soft',
    'Say a programming language',
    'Name a sea creature',
    'Say something you Google',
    'Name a tool',
    'Say a snack',
    'Name something round',
    'Say a winter activity',
    'Name a book genre',
    'Say something that smells good',
    'Name a dance style',
    'Say a kitchen appliance',
    'Name something you fear',
    'Say a mode of transport',
    'Name a body part',
    'Say something you collect',
    'Name a tree',
    'Say a comedy movie',
    'Name something you open with a key',
    'Say a summer activity',
    'Name something electric',
    'Say a type of pasta',
    'Name something you share',
    'Say a famous athlete',
    'Name something that melts',
    'Say a phone setting',
  ],
  fa: [
    'یک میوه بگو',
    'اسم یک فیلم بگو',
    'یک حیوان بگو',
    'اسم یک شهر بگو',
    'چیزی سرد بگو',
    'یک رنگ بگو',
    'یک ورزش بگو',
    'غذایی که دوست نداری بگو',
    'یک ابرقهرمان بگو',
    'یک درس مدرسه بگو',
    'چیزی چسبناک بگو',
    'یک برند ماشین بگو',
    'یک شخصیت کارتونی بگو',
    'کاری که هر صبح می‌کنی بگو',
    'یک ساز موسیقی بگو',
    'اسم یک کشور بگو',
    'چیزی که می‌پوشی بگو',
    'یک نوشیدنی بگو',
    'یک شغل بگو',
    'یک اپ گوشی بگو',
    'چیزی توی آشپزخانه بگو',
    'یک بازی فکری بگو',
    'یک مناسبت بگو',
    'یک تاپینگ پیتزا بگو',
    'چیزی که پرواز می‌کند بگو',
    'یک شبکه اجتماعی بگو',
    'یک دسر بگو',
    'یک برند کفش بگو',
    'چیزی که لب ساحل پیدا می‌شود بگو',
    'یک سریال بگو',
    'یک سبزی بگو',
    'چیزی که صدا می‌دهد بگو',
    'یک سیاره بگو',
    'یک جور هوا بگو',
    'چیزی که برای سفر برمی‌داری بگو',
    'یک اسباب‌بازی بچگی بگو',
    'چیزی تند بگو',
    'یک بنای معروف بگو',
    'یک بازی ویدیویی بگو',
    'کاری که قبل خواب می‌کنی بگو',
    'یک گل بگو',
    'یک نوع پنیر بگو',
    'چیزی گران بگو',
    'یک صبحانه بگو',
    'چیزی نرم بگو',
    'یک زبان برنامه‌نویسی بگو',
    'یک موجود دریایی بگو',
    'چیزی که گوگل می‌کنی بگو',
    'یک ابزار بگو',
    'یک تنقلات بگو',
    'چیزی گرد بگو',
    'یک فعالیت زمستانی بگو',
    'یک ژانر کتاب بگو',
    'چیزی خوشبو بگو',
    'یک سبک رقص بگو',
    'یک وسیله آشپزخانه بگو',
    'چیزی که ازش می‌ترسی بگو',
    'یک وسیله نقلیه بگو',
    'یک قسمت بدن بگو',
    'چیزی که جمع می‌کنی بگو',
    'یک درخت بگو',
    'یک فیلم کمدی بگو',
    'چیزی که با کلید باز می‌شود بگو',
    'یک فعالیت تابستانی بگو',
    'چیزی برقی بگو',
    'یک نوع پاستا بگو',
    'چیزی که با کسی شریک می‌شوی بگو',
    'یک ورزشکار معروف بگو',
    'چیزی که آب می‌شود بگو',
    'یک تنظیمات گوشی بگو',
    'یک غذای ایرانی بگو',
    'یک شاعر بگو',
    'یک تیم فوتبال بگو',
    'چیزی توی یخچال بگو',
    'یک شهر شمالی بگو',
    'یک میان‌وعده بگو',
    'چیزی که تو جیب می‌گذاری بگو',
    'یک برنامه تلویزیونی بگو',
    'چیزی که برای مهمانی می‌خری بگو',
    'یک جمله روزمره بگو',
  ],
}

export function getFusePrompts(locale: Locale): string[] {
  return FUSE_PROMPTS[locale] ?? FUSE_PROMPTS.en
}

export function suggestedLives(playerCount: number) {
  if (playerCount <= 3) return 3
  if (playerCount <= 6) return 2
  return 2
}
