import type { Locale } from '../../store/prefs'
import type { Heat } from '../types'

export type TdKind = 'truth' | 'dare'

export interface TdPrompt {
  id: string
  text: Record<Locale, string>
}

/**
 * Bilingual Truth or Dare decks per heat.
 * Spicy is a real adult deck — the table opts into it on setup, and
 * anyone can always tap Chicken instead of doing a prompt.
 */
const TRUTH_NORMAL: TdPrompt[] = [
  { id: 'tn1', text: { en: 'What’s the most embarrassing thing on your camera roll?', fa: 'خجالت‌آورترین چیزی که تو گالری گوشیته چیه؟' } },
  { id: 'tn2', text: { en: 'What’s a lie you told that you still feel bad about?', fa: 'دروغی که گفتی و هنوز عذاب وجدان داری چیه؟' } },
  { id: 'tn3', text: { en: 'Who in this room would you call to help you hide a body?', fa: 'به کدوم آدم این جمع زنگ می‌زنی که کمکت کنه یه جسد قایم کنی؟' } },
  { id: 'tn4', text: { en: 'What’s the longest you’ve gone without showering?', fa: 'طولانی‌ترین مدتی که حموم نرفتی چقدر بوده؟' } },
  { id: 'tn5', text: { en: 'What’s your most-used excuse for cancelling plans?', fa: 'پرتکرارترین بهونه‌ات برای پیچوندن قرارها چیه؟' } },
  { id: 'tn6', text: { en: 'Have you ever pretended to be sick to skip work or school?', fa: 'تا حالا الکی خودتو مریض جا زدی که سر کار یا مدرسه نری؟' } },
  { id: 'tn7', text: { en: 'What’s the most childish thing you still do?', fa: 'بچگانه‌ترین کاری که هنوز انجام می‌دی چیه؟' } },
  { id: 'tn8', text: { en: 'What’s the weirdest thing you’ve eaten off the floor?', fa: 'عجیب‌ترین چیزی که از رو زمین برداشتی خوردی چیه؟' } },
  { id: 'tn9', text: { en: 'Who was your first crush and what happened?', fa: 'اولین کراشت کی بود و چی شد؟' } },
  { id: 'tn10', text: { en: 'What’s a secret talent nobody here knows about?', fa: 'چه استعداد مخفی‌ای داری که هیچ‌کس اینجا نمی‌دونه؟' } },
  { id: 'tn11', text: { en: 'What’s the dumbest way you’ve injured yourself?', fa: 'احمقانه‌ترین جوری که به خودت آسیب زدی چی بوده؟' } },
  { id: 'tn12', text: { en: 'Have you ever stalked someone here on social media?', fa: 'تا حالا پیج یکی از همین جمع رو زیر و رو کردی؟' } },
  { id: 'tn13', text: { en: 'What’s the pettiest thing you’ve ever done?', fa: 'بچه‌ترین و لجبازترین کاری که کردی چی بوده؟' } },
  { id: 'tn14', text: { en: 'What do you pretend to like but secretly hate?', fa: 'چی رو وانمود می‌کنی دوست داری ولی در واقع ازش متنفری؟' } },
  { id: 'tn15', text: { en: 'What’s your screen time today? Show us.', fa: 'اسکرین‌تایم امروزت چنده؟ نشون بده.' } },
  { id: 'tn16', text: { en: 'What’s the last thing you Googled?', fa: 'آخرین چیزی که گوگل کردی چی بود؟' } },
  { id: 'tn17', text: { en: 'Who in this room has the best style — and who needs help?', fa: 'کی تو این جمع از همه خوش‌استایل‌تره — و کی به کمک نیاز داره؟' } },
  { id: 'tn18', text: { en: 'What’s a rumor you’ve heard about yourself?', fa: 'چه شایعه‌ای درباره خودت شنیدی؟' } },
  { id: 'tn19', text: { en: 'Have you ever cried at work or school? Why?', fa: 'تا حالا سر کار یا مدرسه گریه کردی؟ چرا؟' } },
  { id: 'tn20', text: { en: 'What’s the most you’ve spent on something totally useless?', fa: 'بیشترین پولی که خرج یه چیز کاملاً بی‌مصرف کردی چقدر بوده؟' } },
  { id: 'tn21', text: { en: 'If you had to trade lives with someone here, who and why?', fa: 'اگه مجبور بودی با یکی از این جمع زندگیت رو عوض کنی، کی و چرا؟' } },
  { id: 'tn22', text: { en: 'What’s your guilty-pleasure song? Sing a line.', fa: 'اون آهنگی که یواشکی گوش می‌دی چیه؟ یه تیکه‌شو بخون.' } },
  { id: 'tn23', text: { en: 'What habit of yours annoys people the most?', fa: 'کدوم عادتت بقیه رو بیشتر از همه اذیت می‌کنه؟' } },
  { id: 'tn24', text: { en: 'Have you ever blamed someone else for something you did?', fa: 'تا حالا تقصیر کار خودت رو انداختی گردن یکی دیگه؟' } },
  { id: 'tn25', text: { en: 'What’s the worst gift you’ve ever received?', fa: 'بدترین کادویی که گرفتی چی بوده؟' } },
  { id: 'tn26', text: { en: 'What’s something you’ve never told your parents?', fa: 'چی هست که هیچ‌وقت به پدر و مادرت نگفتی؟' } },
  { id: 'tn27', text: { en: 'Who’s the last person you creeped on before this party?', fa: 'قبل از این مهمونی پیج کی رو دید می‌زدی؟' } },
  { id: 'tn28', text: { en: 'What’s your most irrational fear?', fa: 'غیرمنطقی‌ترین ترست چیه؟' } },
  { id: 'tn29', text: { en: 'Have you ever re-gifted a present? To whom?', fa: 'تا حالا کادویی که گرفتی رو به یکی دیگه دادی؟ به کی؟' } },
  { id: 'tn30', text: { en: 'What’s the longest you’ve worn the same clothes?', fa: 'طولانی‌ترین مدتی که یه لباس رو عوض نکردی چقدره؟' } },
  { id: 'tn31', text: { en: 'What’s something everyone loves that you think is overrated?', fa: 'چی هست که همه عاشقشن ولی به نظرت الکی باد شده؟' } },
  { id: 'tn32', text: { en: 'If your search history was shown on this screen, how bad would it be?', fa: 'اگه هیستوری سرچت رو همین الان نشون بدیم، چقدر افتضاح می‌شه؟' } },
  { id: 'tn33', text: { en: 'What’s the cringiest thing you’ve posted online?', fa: 'خجالت‌آورترین پستی که گذاشتی چی بوده؟' } },
  { id: 'tn34', text: { en: 'Have you ever forgotten someone’s name mid-conversation? Whose?', fa: 'تا حالا وسط حرف اسم طرف رو یادت رفته؟ کی؟' } },
  { id: 'tn35', text: { en: 'What’s the weirdest dream you remember?', fa: 'عجیب‌ترین خوابی که یادته چیه؟' } },
  { id: 'tn36', text: { en: 'Which chat would you least want us to open right now?', fa: 'کدوم چتت رو اصلاً دوست نداری الان باز کنیم؟' } },
  { id: 'tn37', text: { en: 'What’s your most embarrassing nickname ever?', fa: 'ضایع‌ترین لقبی که بهت دادن چی بوده؟' } },
  { id: 'tn38', text: { en: 'Have you ever eaten something you dropped and served it anyway?', fa: 'تا حالا غذایی که افتاده رو برداشتی و به بقیه هم دادی؟' } },
  { id: 'tn39', text: { en: 'What’s one thing you’d change about your personality?', fa: 'یه چیز از شخصیتت که دوست داری عوض شه چیه؟' } },
  { id: 'tn40', text: { en: 'Who here would survive longest in a zombie apocalypse?', fa: 'کی تو این جمع از همه بیشتر تو آخرالزمان زامبی‌ها دووم میاره؟' } },
  { id: 'tn41', text: { en: 'What’s the worst haircut you’ve ever had?', fa: 'بدترین مدل مویی که داشتی چی بوده؟' } },
  { id: 'tn42', text: { en: 'What’s something you own that you’d be embarrassed to show us?', fa: 'چه چیزی داری که خجالت می‌کشی نشونمون بدی؟' } },
  { id: 'tn43', text: { en: 'Have you ever laughed at the worst possible moment? When?', fa: 'تا حالا تو بدترین لحظهٔ ممکن خنده‌ات گرفته؟ کِی؟' } },
  { id: 'tn44', text: { en: 'What’s the most trouble you got into at school?', fa: 'بزرگ‌ترین دردسری که تو مدرسه درست کردی چی بود؟' } },
  { id: 'tn45', text: { en: 'What food do you claim to hate just to look classy?', fa: 'چه غذایی رو الکی می‌گی دوست نداری که باکلاس به نظر بیای؟' } },
  { id: 'tn46', text: { en: 'What’s the last thing you cried about?', fa: 'آخرین باری که گریه کردی برای چی بود؟' } },
  { id: 'tn47', text: { en: 'If you could read one person’s mind here, whose?', fa: 'اگه می‌تونستی ذهن یه نفر از این جمع رو بخونی، کی؟' } },
  { id: 'tn48', text: { en: 'What’s your worst “reply all” or wrong-chat disaster?', fa: 'بدترین سوتیت تو فرستادن پیام به گروه یا آدم اشتباهی چی بوده؟' } },
]

const TRUTH_SPICY: TdPrompt[] = [
  { id: 'ts1', text: { en: 'What’s your body count — honestly?', fa: 'صادقانه بگو — با چند نفر بودی؟' } },
  { id: 'ts2', text: { en: 'Describe your best kiss ever. Who was it with?', fa: 'بهترین بوسهٔ عمرت رو تعریف کن. با کی بود؟' } },
  { id: 'ts3', text: { en: 'What’s a kink you’ve always wanted to try?', fa: 'چه فانتزی‌ای هست که همیشه دلت می‌خواسته امتحانش کنی؟' } },
  { id: 'ts4', text: { en: 'Where’s the riskiest place you’ve hooked up?', fa: 'پرریسک‌ترین جایی که رابطه داشتی کجا بوده؟' } },
  { id: 'ts5', text: { en: 'Have you ever had a one-night stand? Any regrets?', fa: 'تا حالا رابطهٔ یه‌شبه داشتی؟ پشیمونی؟' } },
  { id: 'ts6', text: { en: 'Who in this room would you kiss if there were zero consequences?', fa: 'اگه هیچ عواقبی نداشت، کی رو تو این جمع می‌بوسیدی؟' } },
  { id: 'ts7', text: { en: 'What’s the dirtiest text you’ve ever sent? Paraphrase it.', fa: 'داغ‌ترین پیامی که فرستادی چی بوده؟ خلاصه‌شو بگو.' } },
  { id: 'ts8', text: { en: 'Have you ever been caught in the act? By whom?', fa: 'تا حالا وسط رابطه مچت رو گرفتن؟ کی؟' } },
  { id: 'ts9', text: { en: 'What’s your biggest turn-on?', fa: 'چی بیشتر از همه حشریت می‌کنه؟' } },
  { id: 'ts10', text: { en: 'What’s an instant turn-off, even if the person is hot?', fa: 'چی حتی از یه آدم جذاب هم آنتی‌حالت می‌کنه؟' } },
  { id: 'ts11', text: { en: 'Have you ever sexted someone you’d just met?', fa: 'تا حالا با کسی که تازه آشنا شدی سکس‌چت کردی؟' } },
  { id: 'ts12', text: { en: 'What’s the wildest thing you’ve done in bed?', fa: 'وحشی‌ترین کاری که تو تخت کردی چی بوده؟' } },
  { id: 'ts13', text: { en: 'Ever had a friends-with-benefits situation? How did it end?', fa: 'تا حالا رابطهٔ دوستی با مزایا داشتی؟ آخرش چی شد؟' } },
  { id: 'ts14', text: { en: 'What celebrity is your hall pass?', fa: 'با کدوم سلبریتی اجازه داری بدون دردسر باشی؟' } },
  { id: 'ts15', text: { en: 'Have you ever hooked up with someone way older or younger?', fa: 'تا حالا با کسی خیلی بزرگ‌تر یا کوچیک‌تر از خودت بودی؟' } },
  { id: 'ts16', text: { en: 'What’s your favorite position — and why?', fa: 'پوزیشن موردعلاقه‌ات چیه — و چرا؟' } },
  { id: 'ts17', text: { en: 'Have you ever faked it? How often?', fa: 'تا حالا ارگاسم الکی جا زدی؟ چند وقت یه بار؟' } },
  { id: 'ts18', text: { en: 'What’s the most scandalous photo on your phone?', fa: 'جنجالی‌ترین عکسی که تو گوشیته چیه؟' } },
  { id: 'ts19', text: { en: 'Ever kissed two different people in the same night?', fa: 'تا حالا تو یه شب دو نفر مختلف رو بوسیدی؟' } },
  { id: 'ts20', text: { en: 'What’s your dirtiest fantasy involving someone in this room?', fa: 'داغ‌ترین فانتزی‌ای که درباره یکی از همین جمع داشتی چیه؟' } },
  { id: 'ts21', text: { en: 'Have you ever hooked up with a friend’s ex?', fa: 'تا حالا با اکسِ یکی از دوستات بودی؟' } },
  { id: 'ts22', text: { en: 'What’s the fastest you’ve gone from meeting someone to kissing them?', fa: 'سریع‌ترین رکوردت از آشنایی تا بوسه چقدر بوده؟' } },
  { id: 'ts23', text: { en: 'Ever been skinny dipping? With whom?', fa: 'تا حالا لخت شنا کردی؟ با کی؟' } },
  { id: 'ts24', text: { en: 'What’s something you’ve done that you’d never tell a partner?', fa: 'چه کاری کردی که هیچ‌وقت به پارتنرت نمی‌گی؟' } },
  { id: 'ts25', text: { en: 'Have you ever had a crush on someone taken? Did anything happen?', fa: 'تا حالا رو کسی که رابطه داشته کراش زدی؟ اتفاقی هم افتاد؟' } },
  { id: 'ts26', text: { en: 'What’s your record for most times in one day?', fa: 'رکوردت تو یه روز چند بار بوده؟' } },
  { id: 'ts27', text: { en: 'Lights on or off — and what else are you particular about?', fa: 'چراغ روشن یا خاموش — دیگه رو چی حساسی؟' } },
  { id: 'ts28', text: { en: 'Have you ever used a dating app while on a date?', fa: 'تا حالا وسط یه قرار، تو اپ دوستیابی چرخیدی؟' } },
  { id: 'ts29', text: { en: 'What’s the longest dry spell you’ve survived?', fa: 'طولانی‌ترین دورهٔ بی‌رابطگیت چقدر بوده؟' } },
  { id: 'ts30', text: { en: 'Ever had a dream about someone in this room? Details.', fa: 'تا حالا خواب یکی از همین جمع رو دیدی؟ با جزئیات.' } },
  { id: 'ts31', text: { en: 'What would you do if you woke up invisible for a day — honestly?', fa: 'اگه یه روز نامرئی می‌شدی، صادقانه چی کار می‌کردی؟' } },
  { id: 'ts32', text: { en: 'What’s the most embarrassing thing that’s happened to you mid-hookup?', fa: 'خجالت‌آورترین اتفاقی که وسط رابطه برات افتاده چیه؟' } },
  { id: 'ts33', text: { en: 'Have you ever ghosted someone right after hooking up?', fa: 'تا حالا بعد از رابطه یهو غیب شدی؟' } },
  { id: 'ts34', text: { en: 'Body, face, or voice — what gets you first?', fa: 'بدن، صورت یا صدا — کدوم اول قلابت می‌کنه؟' } },
  { id: 'ts35', text: { en: 'Ever been walked in on — or walked in on someone?', fa: 'تا حالا سرزده مچ کسی رو گرفتی — یا مچ خودت رو گرفتن؟' } },
  { id: 'ts36', text: { en: 'What’s a place on your body you love being kissed?', fa: 'کجای بدنت رو دوست داری ببوسن؟' } },
  { id: 'ts37', text: { en: 'Have you ever role-played? As what?', fa: 'تا حالا رول‌پلی کردی؟ تو چه نقشی؟' } },
  { id: 'ts38', text: { en: 'What’s the boldest thing you’ve done to get someone’s attention?', fa: 'جسورانه‌ترین کاری که برای جلب توجه یه نفر کردی چی بوده؟' } },
  { id: 'ts39', text: { en: 'Ever sent a risky photo? Did you regret it?', fa: 'تا حالا عکس خطرناک فرستادی؟ پشیمون شدی؟' } },
  { id: 'ts40', text: { en: 'Who taught you your best move — and what is it?', fa: 'بهترین حرکتت رو از کی یاد گرفتی — و چی هست؟' } },
  { id: 'ts41', text: { en: 'Have you ever hooked up somewhere at work or school?', fa: 'تا حالا تو محیط کار یا دانشگاه با کسی رابطه داشتی؟' } },
  { id: 'ts42', text: { en: 'What’s your favorite thing a partner has ever whispered to you?', fa: 'بهترین چیزی که یه پارتنر در گوشت گفته چی بوده؟' } },
  { id: 'ts43', text: { en: 'Rate your own kissing skills out of 10 — and defend it.', fa: 'به مهارت بوسیدنت از ۱۰ چند می‌دی — و ازش دفاع کن.' } },
  { id: 'ts44', text: { en: 'What’s something spicy on your bucket list?', fa: 'چه چیز داغی تو لیست آرزوهاته؟' } },
  { id: 'ts45', text: { en: 'Ever had feelings for two people at once? How did you choose?', fa: 'تا حالا همزمان از دو نفر خوشت اومده؟ چطوری انتخاب کردی؟' } },
  { id: 'ts46', text: { en: 'What’s the most seductive outfit you own?', fa: 'اغواگرترین لباسی که داری چیه؟' } },
  { id: 'ts47', text: { en: 'Morning person or night person — in bed?', fa: 'تو تخت آدمِ صبحی یا شبی؟' } },
  { id: 'ts48', text: { en: 'What’s a secret you’ve kept about your love life until right now?', fa: 'چه رازی از زندگی عاشقانه‌ات رو تا همین الان نگه داشتی؟' } },
]

const DARE_NORMAL: TdPrompt[] = [
  { id: 'dn1', text: { en: 'Do your best impression of someone in this room until someone guesses who.', fa: 'ادای یکی از جمع رو دربیار تا یکی حدس بزنه کیه.' } },
  { id: 'dn2', text: { en: 'Let the group post a story on your Instagram.', fa: 'بذار جمع یه استوری رو پیجت بذاره.' } },
  { id: 'dn3', text: { en: 'Talk in an accent until your next turn.', fa: 'تا نوبت بعدیت با لهجه حرف بزن.' } },
  { id: 'dn4', text: { en: 'Do 15 push-ups right now.', fa: 'همین الان ۱۵ تا شنا برو.' } },
  { id: 'dn5', text: { en: 'Let the player to your left do your hair however they want.', fa: 'بذار نفر سمت چپت هر مدلی خواست موهاتو درست کنه.' } },
  { id: 'dn6', text: { en: 'Call a random contact and sing them happy birthday.', fa: 'به یه مخاطب رندوم زنگ بزن و براش تولدت مبارک بخون.' } },
  { id: 'dn7', text: { en: 'Eat a spoonful of a condiment chosen by the group.', fa: 'یه قاشق از هر سسی که جمع انتخاب کرد بخور.' } },
  { id: 'dn8', text: { en: 'Show the last five photos in your camera roll.', fa: 'پنج‌تا عکس آخر گالریت رو نشون بده.' } },
  { id: 'dn9', text: { en: 'Dance with no music for 30 seconds.', fa: 'سی ثانیه بدون آهنگ برقص.' } },
  { id: 'dn10', text: { en: 'Let someone tickle you for 15 seconds without laughing.', fa: 'بذار یکی ۱۵ ثانیه قلقلکت بده و نباید بخندی.' } },
  { id: 'dn11', text: { en: 'Speak only in questions until your next turn.', fa: 'تا نوبت بعدیت فقط سوالی حرف بزن.' } },
  { id: 'dn12', text: { en: 'Do your best animal impression for 20 seconds.', fa: 'بیست ثانیه ادای یه حیوون رو دربیار.' } },
  { id: 'dn13', text: { en: 'Let the group write a text and send it to anyone they pick.', fa: 'بذار جمع یه پیام بنویسه و به هر کی خواستن بفرسته.' } },
  { id: 'dn14', text: { en: 'Wear your clothes backwards until the game ends.', fa: 'تا آخر بازی لباستو برعکس بپوش.' } },
  { id: 'dn15', text: { en: 'Imitate a TikTok trend the group chooses.', fa: 'یه ترند تیک‌تاک که جمع انتخاب می‌کنه رو اجرا کن.' } },
  { id: 'dn16', text: { en: 'Hold a plank until your next turn.', fa: 'تا نوبت بعدیت پلانک نگه دار.' } },
  { id: 'dn17', text: { en: 'Let someone draw on your face with a pen (washable!).', fa: 'بذار یکی با ماژیک (پاک‌شو!) رو صورتت نقاشی کنه.' } },
  { id: 'dn18', text: { en: 'Talk like a sports commentator narrating the room for one minute.', fa: 'یه دقیقه مثل گزارشگر فوتبال هر چی تو اتاق می‌گذره رو گزارش کن.' } },
  { id: 'dn19', text: { en: 'Do 20 squats while saying the alphabet backwards.', fa: 'بیست تا اسکوات برو و همزمان الفبا رو برعکس بگو.' } },
  { id: 'dn20', text: { en: 'Let the group look through your camera roll for 30 seconds.', fa: 'بذار جمع ۳۰ ثانیه گالریت رو بگرده.' } },
  { id: 'dn21', text: { en: 'Sing everything you say until your next turn.', fa: 'تا نوبت بعدیت هر چی می‌گی رو آواز بخون.' } },
  { id: 'dn22', text: { en: 'Make up a 30-second rap about the person across from you.', fa: 'یه رپ ۳۰ ثانیه‌ای درباره نفر روبه‌روییت بساز.' } },
  { id: 'dn23', text: { en: 'Balance a spoon on your nose for 20 seconds.', fa: 'بیست ثانیه یه قاشق رو روی دماغت نگه دار.' } },
  { id: 'dn24', text: { en: 'Text your mom “I have something to tell you…” and don’t reply for an hour.', fa: 'به مامانت بنویس «باید یه چیزی بهت بگم…» و تا یه ساعت جواب نده.' } },
  { id: 'dn25', text: { en: 'Do a dramatic movie-death scene.', fa: 'یه صحنهٔ مرگ سینماییِ دراماتیک اجرا کن.' } },
  { id: 'dn26', text: { en: 'Let the person to your right give you a new hairstyle with whatever’s nearby.', fa: 'بذار نفر سمت راستت با هر چی دم دسته یه مدل موی جدید بهت بده.' } },
  { id: 'dn27', text: { en: 'Walk like a runway model across the room and back.', fa: 'مثل مدل‌ها تا اون سر اتاق برو و برگرد.' } },
  { id: 'dn28', text: { en: 'Say the alphabet while doing a different dance move for each letter.', fa: 'الفبا رو بگو و برای هر حرف یه حرکت رقص متفاوت بزن.' } },
  { id: 'dn29', text: { en: 'Let the group choose your profile picture for 24 hours.', fa: 'بذار جمع عکس پروفایلت رو برای ۲۴ ساعت انتخاب کنه.' } },
  { id: 'dn30', text: { en: 'Talk without moving your lips until someone understands a full sentence.', fa: 'بدون تکون دادن لب حرف بزن تا یکی یه جملهٔ کامل رو بفهمه.' } },
  { id: 'dn31', text: { en: 'Do your best evil-villain laugh for 15 seconds straight.', fa: 'پونزده ثانیه پشت سر هم مثل شخصیت منفی فیلم‌ها بخند.' } },
  { id: 'dn32', text: { en: 'Wear socks on your hands until your next turn.', fa: 'تا نوبت بعدیت جوراب دستت کن.' } },
  { id: 'dn33', text: { en: 'Let the group give you a new contact name for someone — and keep it a week.', fa: 'بذار جمع اسم یکی از مخاطب‌هات رو عوض کنه — و یه هفته نگهش دار.' } },
  { id: 'dn34', text: { en: 'Recreate the last photo you posted, live.', fa: 'آخرین عکسی که پست کردی رو همین‌جا زنده بازسازی کن.' } },
  { id: 'dn35', text: { en: 'Compliment every player — no repeats, five seconds each.', fa: 'به همهٔ بازیکن‌ها تعریف بگو — تکراری ممنوع، هر کدوم پنج ثانیه.' } },
  { id: 'dn36', text: { en: 'Try to lick your elbow for 20 seconds while keeping a straight face.', fa: 'بیست ثانیه سعی کن آرنجت رو لیس بزنی، بدون خندیدن.' } },
  { id: 'dn37', text: { en: 'Let the youngest player give you any dare of their choice.', fa: 'بذار کوچیک‌ترین بازیکن هر جرئتی خواست بهت بده.' } },
  { id: 'dn38', text: { en: 'Do an ad for the object to your left like a TV shopping host.', fa: 'برای اولین چیزی که سمت چپته مثل مجری تبلیغات تلویزیونی تبلیغ کن.' } },
  { id: 'dn39', text: { en: 'Keep your eyes closed until your next turn.', fa: 'تا نوبت بعدیت چشماتو بسته نگه دار.' } },
  { id: 'dn40', text: { en: 'Send a voice message singing to the third chat in your list.', fa: 'برای سومین چت لیستت یه ویس آواز بفرست.' } },
  { id: 'dn41', text: { en: 'Do the worm — or your best attempt.', fa: 'حرکت کرم رو بزن — یا هر چی ازت برمیاد.' } },
  { id: 'dn42', text: { en: 'Let the group pick a word you can’t say for the rest of the game — one push-up each slip.', fa: 'بذار جمع یه کلمهٔ ممنوعه انتخاب کنه — هر بار گفتی یه شنا برو.' } },
  { id: 'dn43', text: { en: 'Swap an item of clothing with the player across from you.', fa: 'یه تیکه لباس رو با نفر روبه‌روییت عوض کن.' } },
  { id: 'dn44', text: { en: 'Narrate everything you do in third person until your next turn.', fa: 'تا نوبت بعدیت هر کاری می‌کنی رو سوم‌شخص روایت کن.' } },
  { id: 'dn45', text: { en: 'Draw a portrait of another player with your eyes closed — they keep it.', fa: 'با چشم بسته چهرهٔ یه بازیکن رو بکش — و بهش هدیه بده.' } },
  { id: 'dn46', text: { en: 'Do 10 jumping jacks while shouting your own name.', fa: 'ده تا پروانه بزن و همزمان اسمتو داد بزن.' } },
  { id: 'dn47', text: { en: 'Let the group choose an emoji — use it in every message for a day.', fa: 'بذار جمع یه ایموجی انتخاب کنه — تا یه روز تو هر پیامت استفاده‌ش کن.' } },
  { id: 'dn48', text: { en: 'Freeze like a statue whenever anyone claps, until your next turn.', fa: 'تا نوبت بعدیت هر وقت کسی دست زد مثل مجسمه خشک شو.' } },
]

const DARE_SPICY: TdPrompt[] = [
  { id: 'ds1', text: { en: 'Give a willing player a 30-second lap dance.', fa: 'برای یه بازیکن داوطلب ۳۰ ثانیه لپ‌دنس برو.' } },
  { id: 'ds2', text: { en: 'Kiss the neck of a player who’s up for it.', fa: 'گردن یه بازیکنی که پایه‌ست رو ببوس.' } },
  { id: 'ds3', text: { en: 'Remove one item of clothing until your next turn.', fa: 'یه تیکه لباستو تا نوبت بعدیت دربیار.' } },
  { id: 'ds4', text: { en: 'Do your sexiest dance for 30 seconds — full commitment.', fa: 'سی ثانیه سکسی‌ترین رقصتو برو — بدون خجالت.' } },
  { id: 'ds5', text: { en: 'Whisper something dirty in the ear of the player to your left.', fa: 'در گوش نفر سمت چپت یه چیز خیلی داغ بگو.' } },
  { id: 'ds6', text: { en: 'Read your last DM conversation with your crush or partner aloud.', fa: 'آخرین چت با کراش یا پارتنرت رو بلند بخون.' } },
  { id: 'ds7', text: { en: 'Reenact your O-face for the table.', fa: 'قیافهٔ لحظهٔ ارگاسمتو برای جمع اجرا کن.' } },
  { id: 'ds8', text: { en: 'Let another player bite your ear softly.', fa: 'بذار یه بازیکن آروم لالهٔ گوشتو گاز بگیره.' } },
  { id: 'ds9', text: { en: 'Give a slow, sensual massage to a willing player for one minute.', fa: 'یه دقیقه به یه بازیکن داوطلب ماساژ آروم و حسی بده.' } },
  { id: 'ds10', text: { en: 'Demonstrate your favorite kiss technique on your own hand — with sound effects.', fa: 'تکنیک بوسهٔ موردعلاقه‌تو روی دست خودت نشون بده — با افکت صدا.' } },
  { id: 'ds11', text: { en: 'Sit on a willing player’s lap until your next turn.', fa: 'تا نوبت بعدیت رو پای یه بازیکن داوطلب بشین.' } },
  { id: 'ds12', text: { en: 'Send “thinking about you 😏” to the last person you kissed.', fa: 'به آخرین کسی که بوسیدیش بفرست «تو فکرتم 😏».' } },
  { id: 'ds13', text: { en: 'Slow dance with a willing player — no music, full eye contact.', fa: 'با یه بازیکن داوطلب رقص آروم برو — بدون آهنگ، با تماس چشمی کامل.' } },
  { id: 'ds14', text: { en: 'Describe, in detail, what you find attractive about the player across from you.', fa: 'با جزئیات بگو چه چیز نفر روبه‌روییت جذابه.' } },
  { id: 'ds15', text: { en: 'Let the group pose you and a willing player for a “couple photo”.', fa: 'بذار جمع تو و یه بازیکن داوطلب رو برای یه «عکس دونفرهٔ عاشقانه» ژست بده.' } },
  { id: 'ds16', text: { en: 'Take a body shot off a willing player — or let them take one off you.', fa: 'از روی بدن یه بازیکن داوطلب شات بزن — یا بذار اون از روی تو بزنه.' } },
  { id: 'ds17', text: { en: 'Give your best striptease for one song verse — clothes stay on if you dare stop there.', fa: 'یه بند از یه آهنگ رو استریپ‌تیز برو — تا هر جا که جرئتشو داری.' } },
  { id: 'ds18', text: { en: 'Moan another player’s name — convincingly.', fa: 'اسم یه بازیکن رو با ناله بگو — طوری که باورمون شه.' } },
  { id: 'ds19', text: { en: 'Kiss a willing player anywhere they choose.', fa: 'یه بازیکن داوطلب رو هر جا که خودش انتخاب کرد ببوس.' } },
  { id: 'ds20', text: { en: 'Trade seats and feed a willing player something — slowly.', fa: 'جاتو عوض کن و با دستت به یه بازیکن داوطلب یه چیزی بده بخوره — آروم.' } },
  { id: 'ds21', text: { en: 'Show the most scandalous photo of yourself you’re willing to share.', fa: 'جنجالی‌ترین عکسی از خودت که حاضری نشون بدی رو رو کن.' } },
  { id: 'ds22', text: { en: 'Do 10 hip thrusts while keeping eye contact with the player of your choice.', fa: 'ده تا حرکت باسن بزن و همزمان به بازیکنی که انتخاب می‌کنی نگاه کن.' } },
  { id: 'ds23', text: { en: 'Let the player to your right leave a (fake or real) hickey mark with lipstick.', fa: 'بذار نفر سمت راستت با رژ یه جای کبودی (الکی یا واقعی) روی گردنت بذاره.' } },
  { id: 'ds24', text: { en: 'Call your crush or partner and tell them what you’d do if they were here.', fa: 'به کراش یا پارتنرت زنگ بزن و بگو اگه اینجا بود چی کار می‌کردی.' } },
  { id: 'ds25', text: { en: 'Remove a willing player’s sock (or more, if they offer) using only your teeth.', fa: 'فقط با دندون جوراب (یا اگه خودش خواست، بیشتر) یه بازیکن داوطلب رو دربیار.' } },
  { id: 'ds26', text: { en: 'Blindfolded, guess a willing player only by touching their face.', fa: 'با چشم بسته فقط با لمس صورت، حدس بزن کدوم بازیکن داوطلبه.' } },
  { id: 'ds27', text: { en: 'Talk in your bedroom voice until your next turn.', fa: 'تا نوبت بعدیت با صدای تو تختت حرف بزن.' } },
  { id: 'ds28', text: { en: 'Let the group pick two willing players — stare into each other’s eyes for 60 seconds without laughing.', fa: 'جمع دو بازیکن داوطلب انتخاب می‌کنه — ۶۰ ثانیه تو چشم هم زل بزنین بدون خنده.' } },
  { id: 'ds29', text: { en: 'Describe your ideal night — from the first kiss onward.', fa: 'شب ایده‌آلت رو تعریف کن — از اولین بوسه به بعد.' } },
  { id: 'ds30', text: { en: 'Eat something off a willing player’s hand — maintain eye contact.', fa: 'از کف دست یه بازیکن داوطلب یه چیزی بخور — با تماس چشمی.' } },
  { id: 'ds31', text: { en: 'Give a piggyback ride to a willing player while they whisper commands.', fa: 'یه بازیکن داوطلب رو کول کن و هر جا در گوشت گفت ببرش.' } },
  { id: 'ds32', text: { en: 'Text an ex “I still think about that night” — or chicken out.', fa: 'به اکست بنویس «هنوز به اون شب فکر می‌کنم» — یا جا بزن.' } },
  { id: 'ds33', text: { en: 'Let another player untie/undo one thing you’re wearing (shoe, belt, hair tie…).', fa: 'بذار یه بازیکن یه چیز از پوششت رو باز کنه (کفش، کمربند، کش مو…).' } },
  { id: 'ds34', text: { en: 'Act out your go-to move when you want someone to notice you at a party.', fa: 'حرکتی که تو مهمونی برای جلب توجه می‌زنی رو اجرا کن.' } },
  { id: 'ds35', text: { en: 'Kiss the hand of every player like an old-school gentleman/lady.', fa: 'دست همهٔ بازیکن‌ها رو مثل اشراف‌زاده‌های قدیمی ببوس.' } },
  { id: 'ds36', text: { en: 'Sit back-to-back with a willing player and lean all the way into them for a round.', fa: 'یه راند پشت‌به‌پشت یه بازیکن داوطلب بشین و کامل بهش تکیه بده.' } },
  { id: 'ds37', text: { en: 'Rate every player’s attractiveness out of 10 — out loud.', fa: 'به جذابیت همهٔ بازیکن‌ها از ۱۰ نمره بده — بلند.' } },
  { id: 'ds38', text: { en: 'Show the group your sexiest selfie pose and hold it for 10 seconds.', fa: 'سکسی‌ترین ژست سلفیتو بگیر و ده ثانیه نگهش دار.' } },
  { id: 'ds39', text: { en: 'Let a willing player trace a word on your back with a finger — guess it.', fa: 'بذار یه بازیکن داوطلب با انگشت یه کلمه رو پشتت بنویسه — حدسش بزن.' } },
  { id: 'ds40', text: { en: 'Give the player of your choice a kiss on the cheek — in slow motion.', fa: 'به بازیکنی که انتخاب می‌کنی یه بوس اسلوموشن رو گونه بده.' } },
  { id: 'ds41', text: { en: 'Confess the most attractive thing someone in this room has ever done.', fa: 'اعتراف کن جذاب‌ترین کاری که یکی از این جمع کرده چی بوده.' } },
  { id: 'ds42', text: { en: 'Put an ice cube somewhere on a willing player and let it melt.', fa: 'یه تیکه یخ بذار یه جای بدن یه بازیکن داوطلب تا آب شه.' } },
  { id: 'ds43', text: { en: 'Swap shirts with a willing player — in this room, no hiding.', fa: 'با یه بازیکن داوطلب پیرهنتونو عوض کنین — همین‌جا، بدون قایم شدن.' } },
  { id: 'ds44', text: { en: 'Do your most seductive crawl across the room.', fa: 'اغواگرترین حالت چهار دست و پا رو تا اون سر اتاق برو.' } },
  { id: 'ds45', text: { en: 'Let the group write a flirty message to anyone in your contacts.', fa: 'بذار جمع یه پیام لاسی به هر کی از مخاطب‌هات خواستن بفرسته.' } },
  { id: 'ds46', text: { en: 'Blow a slow kiss to every player — make each one different.', fa: 'برای همهٔ بازیکن‌ها بوس بفرست — هر کدوم یه مدل.' } },
  { id: 'ds47', text: { en: 'Reveal your phone wallpaper and lock screen — explain them.', fa: 'والپیپر و لاک‌اسکرین گوشیتو نشون بده — و توضیح بده.' } },
  { id: 'ds48', text: { en: 'For the rest of the game, address the player of your choice only as “babe”.', fa: 'تا آخر بازی، بازیکنی که انتخاب می‌کنی رو فقط «عزیزم» صدا کن.' } },
]

const DECKS: Record<TdKind, Record<Heat, TdPrompt[]>> = {
  truth: { normal: TRUTH_NORMAL, spicy: TRUTH_SPICY },
  dare: { normal: DARE_NORMAL, spicy: DARE_SPICY },
}

export function getTdPrompts(kind: TdKind, heat: Heat): TdPrompt[] {
  return DECKS[kind][heat]
}

export function countTdPrompts(heat: Heat): number {
  return DECKS.truth[heat].length + DECKS.dare[heat].length
}
